"Resource/UI/HUD/LocalPlayerPanel.res"
{
	"ModBg"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"ModBg"
		"xpos"	"0"
		"ypos"	"0"
		"wide"	"120"
		"tall"	"34"
		"zpos"	"-5"
		"visible"	"1"
		"enabled"	"1"
		"fillcolor"	"0 0 0 140"
	}
	"Head"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"Head"
		"xpos"	"3"
		"ypos"	"3"
		"wide"	"28"
		"tall"	"28"
		"visible"	"1"
		"enabled"	"1"
		"scaleImage"	"1"
	}
	"DuckingIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"DuckingIcon"
		"xpos"	"105"
		"ypos"	"3"
		"wide"	"12"
		"tall"	"12"
		"zpos"	"2"
		"visible"	"1"
		"enabled"	"1"
		"scaleImage"	"1"
		"image"	"hud/crouch_survivor"
	}
	"Incapacitated"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"Incapacitated"
		"xpos"	"0"
		"ypos"	"0"
		"wide"	"120"
		"tall"	"34"
		"visible"	"1"
		"enabled"	"1"
		"scaleImage"	"1"
		"zpos"	"0"
	}
	"Health"
	{
		"ControlName"	"HealthPanel"
		"fieldName"	"Health"
		"xpos"	"34"
		"ypos"	"24"
		"wide"	"82"
		"tall"	"6"
		"visible"	"1"
		"enabled"	"1"
		"zpos"	"1"
	}
	"HealthbarTextureTop"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"HealthbarTextureTop"
		"visible"	"0"
		"enabled"	"0"
	}
	"HealthbarTextureBottom"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"HealthbarTextureBottom"
		"visible"	"0"
		"enabled"	"0"
	}
	"HealthIcon"
	{
		"ControlName"	"Label"
		"fieldName"	"HealthIcon"
		"xpos"	"34"
		"ypos"	"4"
		"wide"	"14"
		"tall"	"18"
		"visible"	"1"
		"enabled"	"1"
		"labelText"	","
		"textAlignment"	"west"
		"font"	"L4D_Icons"
		"zpos"	"2"
	}
	"HealthNumber"
	{
		"ControlName"	"Label"
		"fieldName"	"HealthNumber"
		"xpos"	"48"
		"ypos"	"3"
		"wide"	"56"
		"tall"	"20"
		"visible"	"1"
		"enabled"	"1"
		"labelText"	"%HealthNumber%"
		"textAlignment"	"west"
		"font"	"PlayerDisplayHealth"
		"zpos"	"2"
	}
}
