"Resource/UI/HUD/TeammatePanel.res"
{
	"ModBg"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"ModBg"
		"xpos"	"0"
		"ypos"	"0"
		"wide"	"120"
		"tall"	"31"
		"zpos"	"-5"
		"visible"	"1"
		"enabled"	"1"
		"fillcolor"	"0 0 0 140"
	}
	"BackgroundImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"BackgroundImage"
		"xpos"	"0"
		"ypos"	"0"
		"wide"	"120"
		"tall"	"31"
		"zpos"	"-1"
		"visible"	"0"
		"enabled"	"1"
		"fillcolor"	"0 0 0 140"
	}
	"Voice"
	{
		"ControlName"	"Panel"
		"fieldName"	"Voice"
		"xpos"	"108"
		"ypos"	"2"
		"wide"	"10"
		"tall"	"10"
		"visible"	"0"
		"enabled"	"1"
		"zpos"	"3"
	}
	"Head"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"Head"
		"xpos"	"3"
		"ypos"	"3"
		"wide"	"25"
		"tall"	"25"
		"visible"	"1"
		"enabled"	"1"
		"scaleImage"	"1"
	}
	"Incapacitated"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"Incapacitated"
		"xpos"	"32"
		"ypos"	"0"
		"wide"	"88"
		"tall"	"31"
		"visible"	"1"
		"enabled"	"1"
		"scaleImage"	"1"
		"zpos"	"0"
	}
	"Dead"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"Dead"
		"xpos"	"0"
		"ypos"	"0"
		"wide"	"120"
		"tall"	"31"
		"visible"	"1"
		"enabled"	"1"
		"scaleImage"	"1"
		"zpos"	"0"
	}
	"Name"
	{
		"ControlName"	"Label"
		"fieldName"	"Name"
		"xpos"	"32"
		"ypos"	"2"
		"wide"	"54"
		"tall"	"11"
		"visible"	"1"
		"enabled"	"1"
		"labelText"	""
		"textAlignment"	"west"
		"font"	"PlayerDisplayName"
		"zpos"	"3"
		"fgcolor_override"	"White"
	}
	"HealthNumber"
	{
		"ControlName"	"Label"
		"fieldName"	"HealthNumber"
		"xpos"	"86"
		"ypos"	"2"
		"wide"	"30"
		"tall"	"11"
		"visible"	"1"
		"enabled"	"1"
		"labelText"	"%HealthNumber%"
		"textAlignment"	"east"
		"font"	"PlayerDisplayName"
		"zpos"	"3"
		"fgcolor_override"	"White"
	}
	"Health"
	{
		"ControlName"	"HealthPanel"
		"fieldName"	"Health"
		"xpos"	"32"
		"ypos"	"23"
		"wide"	"84"
		"tall"	"5"
		"visible"	"1"
		"enabled"	"1"
		"zpos"	"1"
	}
	"Status"
	{
		"ControlName"	"Label"
		"fieldName"	"Status"
		"xpos"	"32"
		"ypos"	"11"
		"wide"	"84"
		"tall"	"11"
		"visible"	"1"
		"enabled"	"1"
		"labelText"	""
		"textAlignment"	"east"
		"font"	"PlayerDisplayName"
		"zpos"	"3"
		"fgcolor_override"	"White"
	}
	"Items"
	{
		"ControlName"	"Label"
		"fieldName"	"Items"
		"xpos"	"32"
		"ypos"	"10"
		"wide"	"50"
		"tall"	"13"
		"visible"	"1"
		"enabled"	"1"
		"labelText"	""
		"textAlignment"	"west"
		"font"	"L4D_Icons"
		"zpos"	"2"
	}
}
