"Resource/UI/HUD/ZombieHealthLeft_Large.res"
{
	"ModBg"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"ModBg"
		"xpos"	"0"
		"ypos"	"0"
		"wide"	"150"
		"tall"	"34"
		"zpos"	"-5"
		"visible"	"1"
		"enabled"	"1"
		"fillcolor"	"0 0 0 140"
	}
	"BackgroundImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"BackgroundImage"
		"xpos"	"0"
		"ypos"	"0"
		"wide"	"0"
		"tall"	"0"
		"visible"	"0"
		"enabled"	"0"
		"zpos"	"-2"
	}
	"HealthNumber"
	{
		"ControlName"	"Label"
		"fieldName"	"HealthNumber"
		"xpos"	"8"
		"ypos"	"3"
		"wide"	"100"
		"tall"	"20"
		"visible"	"1"
		"enabled"	"1"
		"labelText"	"%HealthNumber%"
		"textAlignment"	"west"
		"font"	"PlayerDisplayHealth"
		"zpos"	"2"
	}
	"Health"
	{
		"ControlName"	"HealthPanel"
		"fieldName"	"Health"
		"xpos"	"8"
		"ypos"	"25"
		"wide"	"134"
		"tall"	"5"
		"visible"	"1"
		"enabled"	"1"
		"zpos"	"1"
	}
	"DuckingIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"DuckingIcon"
		"xpos"	"134"
		"ypos"	"4"
		"wide"	"12"
		"tall"	"12"
		"zpos"	"2"
		"visible"	"1"
		"enabled"	"1"
		"scaleImage"	"1"
		"image"	"hud/crouch_infected"
	}
}
