"Resource/UI/HUD/ZombieTeamDisplayPlayer.res"
{
	"BackgroundImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"BackgroundImage"
		"xpos"	"0"
		"ypos"	"0"
		"wide"	"120"
		"tall"	"31"
		"zpos"	"-5"
		"visible"	"1"
		"enabled"	"1"
		"fillcolor"	"0 0 0 140"
	}
	"ZombieTeamDisplayPlayer"
	{
		"ControlName"	"Panel"
		"fieldName"	"ZombieTeamDisplayPlayer"
		"wide"	"120"
		"tall"	"31"
		"visible"	"1"
		"enabled"	"1"
	}
	"PlayerImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"PlayerImage"
		"xpos"	"3"
		"ypos"	"3"
		"wide"	"25"
		"tall"	"25"
		"zpos"	"3"
		"visible"	"1"
		"enabled"	"1"
		"scaleImage"	"1"
		"fgcolor_override"	"255 255 255 255"
	}
	"SkullIconPlacement"
	{
		"ControlName"	"Panel"
		"fieldName"	"SkullIconPlacement"
		"xpos"	"3"
		"ypos"	"3"
		"wide"	"25"
		"tall"	"25"
		"visible"	"1"
		"enabled"	"1"
	}
	"AbilityProgress"
	{
		"ControlName"	"CircularProgressBar"
		"fieldName"	"AbilityProgress"
		"xpos"	"0"
		"ypos"	"0"
		"wide"	"31"
		"tall"	"31"
		"zpos"	"4"
		"visible"	"1"
		"enabled"	"1"
		"fg_image"	"HUD/PZ_charge_meter"
		"bgcolor_override"	"0 0 0 0"
		"progress"	"0.75"
	}
	"NameLabel"
	{
		"ControlName"	"Label"
		"fieldName"	"NameLabel"
		"xpos"	"32"
		"ypos"	"2"
		"wide"	"54"
		"tall"	"11"
		"zpos"	"3"
		"visible"	"1"
		"enabled"	"1"
		"textAlignment"	"west"
		"font"	"PlayerDisplayName"
		"fgcolor_override"	"255 255 255 255"
	}
	"SpawnTimeLabel"
	{
		"ControlName"	"Label"
		"fieldName"	"SpawnTimeLabel"
		"xpos"	"86"
		"ypos"	"2"
		"wide"	"30"
		"tall"	"11"
		"zpos"	"3"
		"visible"	"1"
		"enabled"	"1"
		"textAlignment"	"east"
		"font"	"PlayerDisplayName"
		"fgcolor_override"	"255 255 255 255"
	}
	"HealthPanel"
	{
		"ControlName"	"HealthPanel"
		"fieldName"	"HealthPanel"
		"xpos"	"32"
		"ypos"	"23"
		"wide"	"84"
		"tall"	"5"
		"zpos"	"1"
		"visible"	"1"
		"enabled"	"1"
	}
	"Dead"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"Dead"
		"xpos"	"0"
		"ypos"	"0"
		"wide"	"120"
		"tall"	"0"
		"zpos"	"3"
		"visible"	"1"
		"enabled"	"1"
		"scaleImage"	"1"
		"image"	"hud/overlay_dead"
	}
	"Voice"
	{
		"ControlName"	"Panel"
		"fieldName"	"Voice"
		"xpos"	"108"
		"ypos"	"13"
		"wide"	"10"
		"tall"	"10"
		"zpos"	"3"
		"visible"	"1"
		"enabled"	"1"
		"voice_icon"	"voice_player"
	}
}
