import { describe, it, expect, afterEach } from 'vitest';
import dgram from 'node:dgram';
import { LogListener } from '../src/logListener.js';
import type { LogEvent } from '../src/logParse.js';

const TOKEN = '0123456789abcdef0123456789abcdef';
const OTHER = 'ffffffffffffffffffffffffffffffff';

function send(port: number, body: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const c = dgram.createSocket('udp4');
    const text = Buffer.from(`L 07/30/2026 - 14:23:01: ${body}\n`, 'utf8');
    const pkt = Buffer.concat([Buffer.from([0xff, 0xff, 0xff, 0xff, 0x52]), text]);
    c.send(pkt, port, '127.0.0.1', (err) => { c.close(); err ? reject(err) : resolve(); });
  });
}

let listener: LogListener | null = null;
afterEach(async () => { if (listener) await listener.close(); listener = null; });

describe('LogListener', () => {
  it('delivers events for a registered token and drops others', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0);
    listener.register(TOKEN);

    await send(port, `PUG ${TOKEN} HEARTBEAT`);
    await send(port, `PUG ${OTHER} HEARTBEAT`);
    await send(port, 'some other log line');
    await send(port, `PUG ${TOKEN} MATCH_END a=1 b=2 winner=a`);

    await new Promise((r) => setTimeout(r, 50));

    expect(got).toEqual([
      { kind: 'heartbeat', token: TOKEN },
      { kind: 'match_end', token: TOKEN, a: 1, b: 2, winner: 'a' },
    ]);
  });

  it('stops delivering after unregister', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0);
    listener.register(TOKEN);
    listener.unregister(TOKEN);
    await send(port, `PUG ${TOKEN} HEARTBEAT`);
    await new Promise((r) => setTimeout(r, 50));
    expect(got).toEqual([]);
  });
});

describe('LogListener: self-started match admission', () => {
  const settle = () => new Promise((r) => setTimeout(r, 60));

  it('accepts the self-start burst from an allowed source with an unknown token', async () => {
    // A self-started match's token is generated by the PLUGIN, so the backend
    // cannot have registered it in advance. Admission is by source address.
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    listener.allowMatchCreateFrom('127.0.0.1');

    await send(port, `PUG ${OTHER} MATCH_CREATE map=l4d_vs_farm01_hilltop players=1`);
    await send(port, `PUG ${OTHER} MATCH_ROSTER steamid=76561198030413993 team=a name=volence`);
    await send(port, `PUG ${OTHER} MATCH_CREATE_END players=1`);
    await settle();

    expect(got.map((e) => e.kind)).toEqual(['match_create', 'match_roster', 'match_create_end']);
  });

  it('drops the self-start burst when no source is allowed', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    // no allowMatchCreateFrom call

    await send(port, `PUG ${OTHER} MATCH_CREATE map=l4d_vs_farm01_hilltop players=1`);
    await settle();

    expect(got).toEqual([]);
  });

  it('still drops ordinary lines with an unknown token even from an allowed source', async () => {
    // Only the create burst may bypass token registration. A spoofed
    // MATCH_END or MAP_RESULT must not be able to invent scores.
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    listener.allowMatchCreateFrom('127.0.0.1');

    await send(port, `PUG ${OTHER} MATCH_END a=999 b=0 winner=a`);
    await send(port, `PUG ${OTHER} MAP_RESULT map=l4d_vs_farm01_hilltop a=999 b=0`);
    await send(port, `PUG ${OTHER} HEARTBEAT`);
    await settle();

    expect(got).toEqual([]);
  });

  it('drops the self-start burst from a source that is not allowed', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    listener.allowMatchCreateFrom('203.0.113.7');

    await send(port, `PUG ${OTHER} MATCH_CREATE map=l4d_vs_farm01_hilltop players=1`);
    await settle();

    expect(got).toEqual([]);
  });

  it('a registered token still works regardless of the allowlist', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    listener.register(TOKEN);

    await send(port, `PUG ${TOKEN} HEARTBEAT`);
    await settle();

    expect(got.map((e) => e.kind)).toEqual(['heartbeat']);
  });
});
