import { describe, it, expect, afterEach } from 'vitest';
import dgram from 'node:dgram';
import { LogListener } from '../src/logListener.js';
import type { LogEvent } from '../src/logParse.js';

const TOKEN = '0123456789abcdef0123456789abcdef';
const OTHER = 'ffffffffffffffffffffffffffffffff';

function send(port: number, body: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const c = dgram.createSocket('udp4');
    const text = Buffer.from(`L 07/30/2026 - 14:23:01: ${body}\n`, 'utf8');
    const pkt = Buffer.concat([Buffer.from([0xff, 0xff, 0xff, 0xff, 0x52]), text]);
    c.send(pkt, port, '127.0.0.1', (err) => { c.close(); err ? reject(err) : resolve(); });
  });
}

let listener: LogListener | null = null;
afterEach(async () => { if (listener) await listener.close(); listener = null; });

describe('LogListener', () => {
  it('delivers events for a registered token and drops others', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0);
    listener.register(TOKEN);

    await send(port, `PUG ${TOKEN} HEARTBEAT`);
    await send(port, `PUG ${OTHER} HEARTBEAT`);
    await send(port, 'some other log line');
    await send(port, `PUG ${TOKEN} MATCH_END a=1 b=2 winner=a`);

    await new Promise((r) => setTimeout(r, 50));

    expect(got).toEqual([
      { kind: 'heartbeat', token: TOKEN },
      { kind: 'match_end', token: TOKEN, a: 1, b: 2, winner: 'a' },
    ]);
  });

  it('stops delivering after unregister', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0);
    listener.register(TOKEN);
    listener.unregister(TOKEN);
    await send(port, `PUG ${TOKEN} HEARTBEAT`);
    await new Promise((r) => setTimeout(r, 50));
    expect(got).toEqual([]);
  });
});

describe('LogListener: self-started match admission', () => {
  const settle = () => new Promise((r) => setTimeout(r, 60));

  it('accepts the self-start burst from an allowed source with an unknown token', async () => {
    // A self-started match's token is generated by the PLUGIN, so the backend
    // cannot have registered it in advance. Admission is by source address.
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    listener.allowMatchCreateFrom('127.0.0.1');

    await send(port, `PUG ${OTHER} MATCH_CREATE map=l4d_vs_farm01_hilltop players=1`);
    await send(port, `PUG ${OTHER} MATCH_ROSTER steamid=76561198030413993 team=a name=volence`);
    await send(port, `PUG ${OTHER} MATCH_CREATE_END players=1`);
    await settle();

    expect(got.map((e) => e.kind)).toEqual(['match_create', 'match_roster', 'match_create_end']);
  });

  it('does not take a self-start burst typed into chat on an allowed server', async () => {
    // Chat leaves the box from the very address the allowlist trusts, and the
    // forger picks the token, so neither gate can stop this. The parser does.
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    listener.allowMatchCreateFrom('127.0.0.1');
    const port = await listener.listen(0);
    const say = (text: string) => send(port, `"mallory<7><STEAM_1:0:5><Survivor>" say "${text} x"`);
    await say(`PUG ${OTHER} MATCH_CREATE map=l4d_vs_hospital01_apartment players=1`);
    await say(`PUG ${OTHER} MATCH_ROSTER steamid=76561198000000001 team=a name=victim`);
    await say(`PUG ${OTHER} MATCH_CREATE_END players=1`);
    await settle();
    expect(got).toEqual([]);
  });

  it('drops the self-start burst when no source is allowed', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    // no allowMatchCreateFrom call

    await send(port, `PUG ${OTHER} MATCH_CREATE map=l4d_vs_farm01_hilltop players=1`);
    await settle();

    expect(got).toEqual([]);
  });

  it('still drops ordinary lines with an unknown token even from an allowed source', async () => {
    // Only the create burst may bypass token registration. A spoofed
    // MATCH_END or MAP_RESULT must not be able to invent scores.
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    listener.allowMatchCreateFrom('127.0.0.1');

    await send(port, `PUG ${OTHER} MATCH_END a=999 b=0 winner=a`);
    await send(port, `PUG ${OTHER} MAP_RESULT map=l4d_vs_farm01_hilltop a=999 b=0`);
    await send(port, `PUG ${OTHER} HEARTBEAT`);
    await settle();

    expect(got).toEqual([]);
  });

  it('drops the self-start burst from a source that is not allowed', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    listener.allowMatchCreateFrom('203.0.113.7');

    await send(port, `PUG ${OTHER} MATCH_CREATE map=l4d_vs_farm01_hilltop players=1`);
    await settle();

    expect(got).toEqual([]);
  });

  it('a registered token still works regardless of the allowlist', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    listener.register(TOKEN);

    await send(port, `PUG ${TOKEN} HEARTBEAT`);
    await settle();

    expect(got.map((e) => e.kind)).toEqual(['heartbeat']);
  });
});

describe('LogListener: token-less lines are admitted by source address alone', () => {
  const settle = () => new Promise((r) => setTimeout(r, 60));
  const DROP = 'L4DC SIGNON_DROP steamid=76561198030413993 secs=14 forced=651 name=volence';
  const ENTERED = '"volence<61><STEAM_1:1:35074132><>" entered the game';

  it('delivers SIGNON_DROP and "entered the game" from an allowed source', async () => {
    const got: Array<{ ev: LogEvent; source: string }> = [];
    listener = new LogListener((ev, source) => got.push({ ev, source }));
    const port = await listener.listen(0, '127.0.0.1');
    listener.allowMatchCreateFrom('127.0.0.1');

    await send(port, DROP);
    await send(port, ENTERED);
    await settle();

    expect(got).toEqual([
      { ev: { kind: 'signon_drop', steamid: '76561198030413993', secs: 14, forced: 651, name: 'volence' }, source: '127.0.0.1' },
      { ev: { kind: 'entered', steamid: '76561198030413993' }, source: '127.0.0.1' },
    ]);
  });

  // PUGNET is emitted for every human connect, match or not, so it has no
  // token to gate on and the sender's address is the only thing admitting it.
  it('delivers PUGNET from an allowed source and drops it from anywhere else', async () => {
    const line = 'PUGNET steamid=76561198030413993 ip=203.0.113.9 cc=US';

    const allowed: LogEvent[] = [];
    listener = new LogListener((ev) => allowed.push(ev));
    let port = await listener.listen(0, '127.0.0.1');
    listener.allowMatchCreateFrom('127.0.0.1');
    await send(port, line);
    await settle();
    expect(allowed).toEqual([
      { kind: 'player_net', steamid: '76561198030413993', ip: '203.0.113.9', country: 'US' },
    ]);

    await listener.close();
    const denied: LogEvent[] = [];
    listener = new LogListener((ev) => denied.push(ev));
    port = await listener.listen(0, '127.0.0.1');
    await send(port, line);
    await settle();
    expect(denied).toEqual([]);
  });

  it('admits them through the per-datagram predicate too', async () => {
    // A game server added to the database after boot is only known to the
    // predicate, never to the fixed set.
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    listener.allowMatchCreateWhen((address) => address === '127.0.0.1');

    await send(port, DROP);
    await settle();

    expect(got.map((e) => e.kind)).toEqual(['signon_drop']);
  });

  it('drops them when no source is allowed', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');

    await send(port, DROP);
    await send(port, ENTERED);
    await settle();

    expect(got).toEqual([]);
  });

  it('drops them from a source that is not allowed', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    listener.allowMatchCreateFrom('203.0.113.7');

    await send(port, DROP);
    await send(port, ENTERED);
    await settle();

    expect(got).toEqual([]);
  });

  it('a registered token buys a token-less line nothing', async () => {
    // The token gate and the address gate are separate. A live match on the
    // box must not open the address gate for everyone else.
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    listener.register(TOKEN);

    await send(port, DROP);
    await send(port, `PUG ${TOKEN} HEARTBEAT`);
    await settle();

    expect(got.map((e) => e.kind)).toEqual(['heartbeat']);
  });
});

// Two srcds on one machine share an address, and srcds sends its log datagrams
// from its game socket, so the sender's port is what tells them apart.
describe('LogListener: the sender port rides along', () => {
  it("hands the callback the datagram's source port", async () => {
    const got: number[] = [];
    listener = new LogListener((_ev, _source, meta) => got.push(meta.port));
    const port = await listener.listen(0, '127.0.0.1');
    listener.register(TOKEN);
    const c = dgram.createSocket('udp4');
    await new Promise<void>((r) => c.bind(0, '127.0.0.1', () => r()));
    const from = c.address().port;
    const pkt = Buffer.from(`L 07/30/2026 - 14:23:01: PUG ${TOKEN} HEARTBEAT\n`, 'utf8');
    await new Promise<void>((resolve, reject) => c.send(pkt, port, '127.0.0.1', (err) => (err ? reject(err) : resolve())));
    await new Promise((r) => setTimeout(r, 60));
    c.close();
    expect(got).toEqual([from]);
  });
});

describe('LogListener: client settings', () => {
  it('admits an L4DV line only from a game server address, like every token-less line', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    await send(port, 'L4DV id=76561198030413993 cvar=cpu_level value=0');
    await new Promise((r) => setTimeout(r, 60));
    expect(got).toEqual([]);
    listener.allowMatchCreateFrom('127.0.0.1');
    await send(port, 'L4DV id=76561198030413993 cvar=cpu_level value=0');
    await new Promise((r) => setTimeout(r, 60));
    expect(got).toMatchObject([{ kind: 'cvar_flag', cvar: 'cpu_level', value: 0 }]);
  });
});

describe('LogListener: the authenticator', () => {
  const settle = () => new Promise((r) => setTimeout(r, 60));
  const LILAC = 'L4DL id=76561198030413993 cheat=3 banned=1';

  it('drops what it refuses before any gate sees it, token or no token', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    listener.allowMatchCreateFrom('127.0.0.1');
    listener.register(TOKEN);
    listener.setAuthenticator(() => ({ accept: false, serverId: null }));
    await send(port, LILAC);
    await send(port, `PUG ${TOKEN} MATCH_END a=1 b=2 winner=b`);
    await settle();
    expect(got).toEqual([]);
  });

  it('hands it the parsed event, the trailer and where the datagram came from, and passes its server on', async () => {
    const seen: any[] = [];
    const metas: any[] = [];
    listener = new LogListener((_ev, _source, meta) => metas.push(meta));
    const port = await listener.listen(0, '127.0.0.1');
    listener.allowMatchCreateFrom('127.0.0.1');
    listener.setAuthenticator((input) => { seen.push(input); return { accept: true, serverId: 4 }; });
    await send(port, `${LILAC} lseq=1790000000.7 mac=0a1b2c3d`);
    await settle();
    expect(seen).toHaveLength(1);
    expect(seen[0].ev).toMatchObject({ kind: 'lilac_flag' });
    expect(seen[0].trailer).toMatchObject({ boot: 1790000000, seq: 7, mac: '0a1b2c3d' });
    expect(seen[0].address).toBe('127.0.0.1');
    expect(metas[0].serverId).toBe(4);
  });

  it('is an extra gate, not a replacement: a signed line from an address nobody knows is still refused', async () => {
    const got: LogEvent[] = [];
    listener = new LogListener((ev) => got.push(ev));
    const port = await listener.listen(0, '127.0.0.1');
    listener.setAuthenticator(() => ({ accept: true, serverId: 1 }));
    await send(port, LILAC);
    await settle();
    expect(got).toEqual([]);
  });
});
