// GENERATED by scripts/export-hud-art.py. Do not edit; rerun the script.
// Material name (lower case, relative to materials/, no extension), or icon/item/* for an item glyph, -> png in this folder.
export const ART: Record<string, string> = {
  'icon/item/medkit': 'icon-item-medkit.png',
  'icon/item/molotov': 'icon-item-molotov.png',
  'icon/item/pills': 'icon-item-pills.png',
  'icon/item/pipebomb': 'icon-item-pipebomb.png',
  'vgui/healthbar_green': 'vgui-healthbar_green.png',
  'vgui/healthbar_grey': 'vgui-healthbar_grey.png',
  'vgui/healthbar_orange': 'vgui-healthbar_orange.png',
  'vgui/healthbar_red': 'vgui-healthbar_red.png',
  'vgui/healthbar_white': 'vgui-healthbar_white.png',
  'vgui/hud/detail_scratches_bottom_1': 'vgui-hud-detail_scratches_bottom_1.png',
  'vgui/hud/detail_scratches_top_1': 'vgui-hud-detail_scratches_top_1.png',
  'vgui/hud/healthbar_bg_1': 'vgui-hud-healthbar_bg_1.png',
  'vgui/hud/healthbar_bg_2': 'vgui-hud-healthbar_bg_2.png',
  'vgui/hud/healthbar_bg_3': 'vgui-hud-healthbar_bg_3.png',
  'vgui/hud/healthbar_bg_4': 'vgui-hud-healthbar_bg_4.png',
  'vgui/hud/infected_healthbar_bg_1': 'vgui-hud-infected_healthbar_bg_1.png',
  'vgui/hud/overlay_dead': 'vgui-hud-overlay_dead.png',
  'vgui/hud/pz_healthbar_250': 'vgui-hud-pz_healthbar_250.png',
  'vgui/hud/pz_healthbar_3000': 'vgui-hud-pz_healthbar_3000.png',
  'vgui/hud/pz_healthbar_50': 'vgui-hud-pz_healthbar_50.png',
  'vgui/hud/scalablepanel_bgmidgrey': 'vgui-hud-scalablepanel_bgmidgrey.png',
  'vgui/hud/scalablepanel_bgmidgrey_glow': 'vgui-hud-scalablepanel_bgmidgrey_glow.png',
  'vgui/s_panel_background': 'vgui-s_panel_background.png',
  'vgui/s_panel_biker': 'vgui-s_panel_biker.png',
  'vgui/s_panel_biker_incap': 'vgui-s_panel_biker_incap.png',
  'vgui/s_panel_dead': 'vgui-s_panel_dead.png',
  'vgui/s_panel_manager': 'vgui-s_panel_manager.png',
  'vgui/s_panel_manager_incap': 'vgui-s_panel_manager_incap.png',
  'vgui/s_panel_namvet': 'vgui-s_panel_namvet.png',
  'vgui/s_panel_namvet_incap': 'vgui-s_panel_namvet_incap.png',
  'vgui/s_panel_teenangst': 'vgui-s_panel_teenangst.png',
  'vgui/s_panel_teenangst_incap': 'vgui-s_panel_teenangst_incap.png',
};

// Item icon glyphs: how far each one advances the row, and the space the game puts
// between two, as a fraction of the font cell height the PNGs are drawn at.
export const ICON_ADVANCE: Record<string, number> = {
  'icon/item/medkit': 0.8076,
  'icon/item/molotov': 0.7544,
  'icon/item/pills': 0.4644,
  'icon/item/pipebomb': 0.7798,
};

export const ICON_SPACE = 0.2954;

export const ART_TOTAL_BYTES = 217174;
