#!/usr/bin/env python3
"""
Export the HUD textures the editor's preview draws, from the owner's own copy of
pak01, to PNGs under web/src/hud/art/, plus a generated TypeScript index.

Preview only. These files never enter a build: build.ts does not import them and
a test says so. The list below is the only way a texture gets in here, and the
script refuses to write more than 1 MB in total so a mistake cannot bloat the
page. Run by hand, from the repo root:

    /home/volence/l4d/hud/.venv/bin/python scripts/export-hud-art.py

Requires the game installed at the Steam path below. Never run this on a server.
"""
import io, json, os, sys
import vpk
from srctools.vtf import VTF

PAK = os.path.expanduser('~/.steam/steam/steamapps/common/left 4 dead/left4dead/pak01_dir.vpk')
OUT = os.path.join(os.path.dirname(__file__), '..', 'web', 'src', 'hud', 'art')
CAP = 1_000_000

# Lower-case material names, relative to materials/, no extension. Keep this list
# identical to NEEDED_MATERIALS in web/src/hud/art.ts; art.test.ts checks the index
# covers every one of those, so a name added there without being added here fails.
MATERIALS = [
    # survivor portraits: game code chooses one of these for every Head / PlayerImage
    'vgui/s_panel_biker', 'vgui/s_panel_manager', 'vgui/s_panel_namvet', 'vgui/s_panel_teenangst',
    # panel backgrounds and bar frames named by the .res files
    'vgui/s_panel_background',
    'vgui/hud/healthbar_bg_1', 'vgui/hud/healthbar_bg_2', 'vgui/hud/healthbar_bg_3', 'vgui/hud/healthbar_bg_4',
    'vgui/hud/infected_healthbar_bg_1',
    'vgui/hud/pz_healthbar_50', 'vgui/hud/pz_healthbar_250', 'vgui/hud/pz_healthbar_3000',
    'vgui/hud/detail_scratches_top_1', 'vgui/hud/detail_scratches_bottom_1',
    'vgui/hud/overlay_dead',
    # bar fills, named by game code
    'vgui/healthbar_green', 'vgui/healthbar_orange', 'vgui/healthbar_red', 'vgui/healthbar_white', 'vgui/healthbar_grey',
    # weapon boxes, the advanced-mode slots
    'vgui/hud/scalablepanel_bgmidgrey', 'vgui/hud/scalablepanel_bgmidgrey_glow',
    # state panels the advanced-mode slots can restyle (drawn nowhere yet, exported so the index is complete)
    'vgui/s_panel_dead',
    'vgui/s_panel_biker_incap', 'vgui/s_panel_manager_incap', 'vgui/s_panel_namvet_incap', 'vgui/s_panel_teenangst_incap',
]

def main() -> int:
    pak = vpk.open(PAK)
    # Everything is exported in memory first, so a failure (a missing texture,
    # the size cap) leaves the folder exactly as it was.
    exported: dict[str, bytes] = {}
    total = 0
    for name in MATERIALS:
        raw = pak['materials/%s.vtf' % name].read()
        img = VTF.read(io.BytesIO(raw)).get().to_PIL().convert('RGBA')
        buf = io.BytesIO(); img.save(buf, 'PNG', optimize=True)
        data = buf.getvalue()
        total += len(data)
        if total > CAP:
            sys.exit('refusing: total exceeds %d bytes at %s' % (CAP, name))
        exported[name] = data
        print('  %-48s %4dx%-4d %6d bytes' % (name, img.width, img.height, len(data)))
    # art.ts bundles every PNG in the folder (import.meta.glob), not just the
    # ones the index names, so a PNG left over from an older list would ship
    # to the page and could push it past the cap. The folder is cleared of
    # PNGs before the new set is written.
    os.makedirs(OUT, exist_ok=True)
    for old in os.listdir(OUT):
        if old.lower().endswith('.png'):
            os.remove(os.path.join(OUT, old))
    index: dict[str, str] = {}
    for name, data in exported.items():
        fname = name.replace('/', '-') + '.png'
        with open(os.path.join(OUT, fname), 'wb') as f: f.write(data)
        index[name] = fname
    lines = ['// GENERATED by scripts/export-hud-art.py. Do not edit; rerun the script.',
             '// Material name (lower case, relative to materials/, no extension) -> png in this folder.',
             'export const ART: Record<string, string> = {']
    for k in sorted(index): lines.append("  '%s': '%s'," % (k, index[k]))
    lines += ['};', '', 'export const ART_TOTAL_BYTES = %d;' % total, '']
    with open(os.path.join(OUT, 'index.ts'), 'w') as f: f.write('\n'.join(lines))
    print('%d textures, %d bytes total' % (len(index), total))
    return 0

if __name__ == '__main__':
    sys.exit(main())
