#!/usr/bin/env python3
"""
Write web/src/hud/stockVgui.ts: the names of every material and texture file the
game ships under materials/vgui/ (lower case, forward slashes, relative to
materials/, with the extension), from the base game's and the DLCs' pak01 and
the loose folders Steam installs. The language folders are left out, because
only players of that language have them.

The import check (web/src/hud/materials.ts) uses it to tell a picture the game
already has from one an imported HUD names but does not include, which the game
draws as a purple and black checkerboard.

Run by hand, from the repo root, with the game installed at the Steam path below:

    /home/volence/l4d/hud/.venv/bin/python scripts/export-stock-vgui.py
"""
import os
import vpk

GAME = os.path.expanduser('~/.steam/steam/steamapps/common/left 4 dead')
FOLDERS = ['left4dead', 'left4dead_dlc3', 'left4dead_dlc4']
OUT = 'web/src/hud/stockVgui.ts'

names = set()
for folder in FOLDERS:
    pak = os.path.join(GAME, folder, 'pak01_dir.vpk')
    if os.path.exists(pak):
        for path in vpk.open(pak):
            p = path.lower().replace('\\', '/')
            if p.startswith('materials/vgui/') and p.endswith(('.vmt', '.vtf')):
                names.add(p[len('materials/'):])
    loose = os.path.join(GAME, folder, 'materials', 'vgui')
    for root, _, files in os.walk(loose):
        for f in files:
            if f.lower().endswith(('.vmt', '.vtf')):
                rel = os.path.relpath(os.path.join(root, f), os.path.join(GAME, folder, 'materials'))
                names.add(rel.lower().replace(os.sep, '/'))

if len(names) < 1000:
    raise SystemExit(f'only {len(names)} files found: is the game installed at {GAME}?')

with open(OUT, 'w') as out:
    out.write('// Generated by scripts/export-stock-vgui.py from the game\'s own files. Do not edit.\n')
    out.write('// Every file the game ships under materials/vgui/, relative to materials/, lower case.\n')
    out.write('export const STOCK_VGUI = `\n')
    out.write('\n'.join(sorted(names)))
    out.write('\n`;\n')
print(f'{len(names)} files written to {OUT}')
