#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>
#include <sdktools>
#include <l4d_consistency>

#define PLUGIN_VERSION "0.2.1"

/**
 * Phase 2: force the generated list (configs/l4d_consistency.cfg) on every map,
 * and mark the one thing the server can see of a rejection.
 *
 * L4D1's engine has sv_consistency, CDownloadListGenerator::ForceExactFile and the
 * client-side check, but bin/server.so never asks for a single file to be checked,
 * so out of the box the enforced list is empty and the feature looks dead. The
 * extension supplies the missing call; Phase 1 proved the client honours it for
 * every file type the list uses (.vmt .vtf .mdl .pcf .wav .txt).
 *
 * The CLIENT does the check, at first connect and again at every level change. On
 * a mismatch it shows "Server is enforcing consistency for this file: <path>" and
 * drops itself. The reason that reaches the server is the plain "Disconnect by
 * user.", so the file name can never be logged here. What can be seen is the
 * signature: a human who left by their own hand without ever being in game on a
 * map that forced files. A cancelled loading screen looks identical, so the line
 * this emits is a hint for the web to weigh, never an accusation.
 *
 * Nothing here bans or kicks. The engine either disconnects the client or it does
 * not.
 *
 * The list is generated by scripts/gen-consistency-list.ts and read verbatim. No
 * wildcards at runtime: a glob that matches nothing is a silent zero, and a silent
 * zero is exactly how this feature looked dead for fifteen years.
 */

#define MAX_GROUPS 16
#define CFG_PATH "configs/l4d_consistency.cfg"
#define SELF_DISCONNECT "Disconnect by user."

ConVar g_cvEnabled;

int g_iGroups;
char g_sGroupTitle[MAX_GROUPS][96];
int g_iGroupListed[MAX_GROUPS];
int g_iGroupForced[MAX_GROUPS];
int g_iForcedThisMap;
int g_iUnresolvedThisMap;
int g_iNotInTable;

public Plugin myinfo =
{
	name = "L4D1 File Consistency",
	author = "Riverside",
	description = "Forces the generated file list for consistency checking and marks signon drops",
	version = PLUGIN_VERSION,
	url = "https://riversidepug.com",
};

public void OnPluginStart()
{
	CreateConVar("l4d_consistency_version", PLUGIN_VERSION, "L4D1 file consistency version",
		FCVAR_NOTIFY | FCVAR_DONTRECORD);

	// Two independent off switches on purpose, this one and sv_consistency.
	// The failure mode of this feature is disconnecting legitimate players, and
	// the recovery path must not require a plugin reload, a rebuild, or anyone
	// who knows C++. This one takes effect at the next map; sv_consistency 0 is
	// the instant one.
	g_cvEnabled = CreateConVar("l4d_consistency_enabled", "1",
		"Force the file list in configs/l4d_consistency.cfg on map start.", FCVAR_NOTIFY, true, 0.0, true, 1.0);

	RegAdminCmd("sm_consistency_status", Cmd_Status, ADMFLAG_ROOT,
		"Report what this plugin forced on the current map, per group.");
	RegAdminCmd("sm_consistency_reload", Cmd_Reload, ADMFLAG_ROOT,
		"Re-read the list and force it now. Paths already forced stay forced until the next map.");
	RegAdminCmd("sm_consistency_force", Cmd_Force, ADMFLAG_ROOT,
		"Force one path right now, for probing a single file.");

	// Pre, so the reason is read before anything else can rewrite the event.
	HookEvent("player_disconnect", Event_PlayerDisconnect, EventHookMode_Pre);
}

public void OnMapStart()
{
	ResetCounts();
	if (!g_cvEnabled.BoolValue) {
		LogMessage("[consistency] disabled by l4d_consistency_enabled, forcing nothing");
		return;
	}
	// After precache, which OnMapStart is. The interface's own comment requires
	// it, and a path forced before precache may be silently ignored.
	ForceList();
}

void ResetCounts()
{
	g_iGroups = 0;
	g_iForcedThisMap = 0;
	g_iUnresolvedThisMap = 0;
	g_iNotInTable = 0;
	for (int i = 0; i < MAX_GROUPS; i++) {
		g_sGroupTitle[i][0] = '\0';
		g_iGroupListed[i] = 0;
		g_iGroupForced[i] = 0;
	}
}

void ForceList()
{
	char cfg[PLATFORM_MAX_PATH];
	BuildPath(Path_SM, cfg, sizeof(cfg), CFG_PATH);
	File f = OpenFile(cfg, "r");
	if (f == null) {
		LogError("[consistency] cannot open %s, forcing nothing", cfg);
		return;
	}

	int table = FindStringTable("downloadables");
	int group = -1;
	char line[PLATFORM_MAX_PATH];
	while (f.ReadLine(line, sizeof(line))) {
		TrimString(line);
		if (line[0] == '\0') {
			continue;
		}
		if (line[0] == '#') {
			// "# group N: title" opens a group. Any other comment is just a comment.
			if (strncmp(line, "# group ", 8) == 0 && g_iGroups < MAX_GROUPS) {
				group = g_iGroups++;
				strcopy(g_sGroupTitle[group], sizeof(g_sGroupTitle[]), line[2]);
			}
			continue;
		}
		if (group < 0) {
			group = g_iGroups++;
			strcopy(g_sGroupTitle[group], sizeof(g_sGroupTitle[]), "ungrouped");
		}
		g_iGroupListed[group]++;

		// Existence is checked against the game's own file system, which covers
		// VPKs, the dlc directories and addons. A path the engine cannot resolve
		// means the list is stale (a game update renamed or removed the file) and
		// must be loud. It is NOT forced: the server would have no CRC to offer,
		// and what a client does with that is not something to find out live.
		if (!FileExists(line, true)) {
			g_iUnresolvedThisMap++;
			LogError("[consistency] not in the game's file system, NOT forced: %s", line);
			continue;
		}
		if (ForceExactFile(line) != 1) {
			LogError("[consistency] ForceExactFile refused '%s'", line);
			continue;
		}
		// The forced paths live in the downloadables string table, and the engine
		// does not report a path it failed to add (table full, or table locked
		// because this ran mid-map). Look each one up rather than trust the call.
		if (table != INVALID_STRING_TABLE && FindStringIndex(table, line) == INVALID_STRING_INDEX) {
			g_iNotInTable++;
			LogError("[consistency] forced but NOT in the downloadables table: %s", line);
			continue;
		}
		g_iGroupForced[group]++;
		g_iForcedThisMap++;
	}
	delete f;

	for (int i = 0; i < g_iGroups; i++) {
		LogMessage("[consistency] %s: forced %d of %d", g_sGroupTitle[i], g_iGroupForced[i], g_iGroupListed[i]);
	}
	LogMessage("[consistency] forced %d files, %d unresolved, %d missing from the table; downloadables table %d of %d; sv_consistency is %s",
		g_iForcedThisMap, g_iUnresolvedThisMap, g_iNotInTable, DownloadablesCount(), DownloadablesMax(),
		GetConVarBool(FindConVar("sv_consistency")) ? "ON" : "OFF -- the engine will not enforce this");
}

int DownloadablesCount()
{
	int table = FindStringTable("downloadables");
	return table == INVALID_STRING_TABLE ? -1 : GetStringTableNumStrings(table);
}

int DownloadablesMax()
{
	int table = FindStringTable("downloadables");
	return table == INVALID_STRING_TABLE ? -1 : GetStringTableMaxStrings(table);
}

/**
 * The signon-drop marker. Everything needed is in the event itself, including
 * the SteamID (networkid), so nothing depends on the order the engine tears the
 * client down in.
 *
 *   L4DC SIGNON_DROP steamid=<id> secs=<connected seconds> forced=<count> name=<rest of line>
 *
 * <id> is a 17 digit SteamID64 when the client slot is still valid, otherwise the
 * event's networkid (STEAM_1:Y:Z). Name is LAST and takes the rest of the line, the same treatment MATCH_ROSTER
 * gives it, so a name cannot forge an earlier field. No match token: a drop
 * mostly happens while people are still joining, before any match exists, which
 * is why this is not an EmitPug line. The web admits it by source address.
 */
public Action Event_PlayerDisconnect(Event event, const char[] name, bool dontBroadcast)
{
	if (g_iForcedThisMap == 0 || event.GetBool("bot")) {
		return Plugin_Continue;
	}
	char reason[128];
	event.GetString("reason", reason, sizeof(reason));
	if (!StrEqual(reason, SELF_DISCONNECT)) {
		return Plugin_Continue; // a timeout or a kick is not the signature
	}
	int client = GetClientOfUserId(event.GetInt("userid"));
	if (client > 0 && IsClientInGame(client)) {
		return Plugin_Continue; // had entered the game: an ordinary leave
	}

	// SteamID64, the form the web keys everything on, whenever the slot can
	// still be asked. validate is false on purpose: a client that drops itself
	// during signon has often not finished Steam validation, and an id that is
	// only good enough for a hint is exactly what this line carries. When the
	// slot is already gone, fall back to the event's networkid, which is the
	// STEAM_1:Y:Z form; the web accepts both and converts.
	char steamid[64], player[MAX_NAME_LENGTH];
	if (client <= 0 || !IsClientConnected(client)
		|| !GetClientAuthId(client, AuthId_SteamID64, steamid, sizeof(steamid), false)) {
		event.GetString("networkid", steamid, sizeof(steamid));
	}
	event.GetString("name", player, sizeof(player));
	if (StrEqual(steamid, "BOT")) {
		return Plugin_Continue;
	}
	int secs = (client > 0 && IsClientConnected(client)) ? RoundToFloor(GetClientTime(client)) : -1;
	LogToGame("L4DC SIGNON_DROP steamid=%s secs=%d forced=%d name=%s", steamid, secs, g_iForcedThisMap, player);
	return Plugin_Continue;
}

public Action Cmd_Status(int client, int args)
{
	ConVar svc = FindConVar("sv_consistency");
	ReplyToCommand(client, "[consistency] enabled: %s, sv_consistency: %s", g_cvEnabled.BoolValue ? "yes" : "no",
		(svc != null && svc.BoolValue) ? "1" : "0");
	for (int i = 0; i < g_iGroups; i++) {
		ReplyToCommand(client, "[consistency] %s: forced %d of %d", g_sGroupTitle[i], g_iGroupForced[i], g_iGroupListed[i]);
	}
	ReplyToCommand(client, "[consistency] forced this map: %d, unresolved: %d, missing from table: %d, downloadables table: %d of %d",
		g_iForcedThisMap, g_iUnresolvedThisMap, g_iNotInTable, DownloadablesCount(), DownloadablesMax());
	return Plugin_Handled;
}

public Action Cmd_Reload(int client, int args)
{
	ResetCounts();
	ForceList();
	ReplyToCommand(client, "[consistency] re-read the list: forced %d, unresolved %d. A path forced earlier this map stays forced until the next map, and connected clients are only checked at their next map load.",
		g_iForcedThisMap, g_iUnresolvedThisMap);
	return Plugin_Handled;
}

public Action Cmd_Force(int client, int args)
{
	if (args < 1) {
		ReplyToCommand(client, "Usage: sm_consistency_force <path>");
		return Plugin_Handled;
	}
	char path[PLATFORM_MAX_PATH];
	GetCmdArg(1, path, sizeof(path));
	int ok = ForceExactFile(path);
	ReplyToCommand(client, "[consistency] ForceExactFile(\"%s\") returned %d%s", path, ok,
		FileExists(path, true) ? "" : " (note: not found in the game file system)");
	return Plugin_Handled;
}
