"""Emit src/mapOverviews.ts from the capture manifests.

Generated rather than hand-written because it is 182 layers across 22 maps, and
because the numbers are read back from the engine at capture time: retyping them
is exactly the kind of transcription error that puts every avatar on a map in the
wrong place while nothing reports an error.

The emitted module has NO imports, deliberately. It is loaded by the browser as
well as the server, and its types are written out structurally so that
src/mapTransform.ts can declare matching named types without either file
importing the other.
"""
import json
import os
import sys

from PIL import Image

src, out = sys.argv[1], sys.argv[2]

# Every capture so far is this size, and the emitted table says so for each
# layer. Asserting it against the real file rather than taking it on trust is
# the point: an off-size capture would otherwise be written out as 2048x1271
# and silently put every avatar on that map in the wrong place, which is the
# exact failure class this generated file exists to prevent.
EXPECTED_SIZE = (2048, 1271)

maps = []
for name in sorted(os.listdir(src)):
    if not name.endswith('.layers.json'):
        continue
    with open(os.path.join(src, name)) as fh:
        m = json.load(fh)
    layers = sorted(m['layers'], key=lambda l: l['cut_height'])
    for layer in layers:
        path = os.path.join(src, layer['image'])
        with Image.open(path) as im:
            size = im.size
        if size != EXPECTED_SIZE:
            raise SystemExit(
                f"{layer['image']} is {size[0]}x{size[1]}, expected "
                f'{EXPECTED_SIZE[0]}x{EXPECTED_SIZE[1]}. Either the capture is '
                'wrong or this generator needs to emit per-layer dimensions.'
            )
        layer['width'], layer['height'] = size
    maps.append((m['map'], layers))

lines = [
    '/**',
    ' * Map overview layers, generated by tools/gen-overviews.py.',
    ' *',
    ' * Do not edit by hand. Every number here is read back from the engine at',
    ' * capture time, so a typo puts every avatar on that map in the wrong place',
    ' * and nothing reports an error.',
    ' *',
    ' * Each map is a stack of horizontal slices cut at different camera heights,',
    ' * ascending. A layer shows everything below its cut height and nothing above,',
    ' * so the right one to draw is the lowest whose cut is still above the players.',
    ' * All layers of a map share one transform, so switching between them needs no',
    ' * repositioning.',
    ' *',
    ' * This module has no imports, deliberately: it is loaded by the browser as',
    ' * well as the server. See src/mapTransform.ts for the matching named types.',
    ' */',
    '',
    'export const OVERVIEWS: Record<string, {',
    '  map: string;',
    '  layers: {',
    '    image: string;',
    '    cutHeight: number;',
    '    unitsPerPixel: number;',
    '    originX: number;',
    '    originY: number;',
    '    width: number;',
    '    height: number;',
    '  }[];',
    '}> = {',
]

for map_name, layers in maps:
    lines.append(f"  '{map_name}': {{")
    lines.append(f"    map: '{map_name}',")
    lines.append('    layers: [')
    for l in layers:
        ulx, uly = l['world_upper_left']
        img = l['image'].replace('.png', '.webp')
        lines.append(
            '      { '
            f"image: '/overviews/{img}', "
            f"cutHeight: {l['cut_height']:g}, "
            f"unitsPerPixel: {l['units_per_pixel']:.6f}, "
            f"originX: {ulx:g}, originY: {uly:g}, "
            f"width: {l['width']}, height: {l['height']} }},"
        )
    lines.append('    ],')
    lines.append('  },')

lines += [
    '};',
    '',
    '/** The overview stack for a map, or null when there is no art for it.',
    ' *',
    ' *  Keys are the names the server reports, including the `vs_` infix for versus',
    ' *  maps and the co-op names for Crash Course, which ships no versus variant. The',
    ' *  second-chance lookup exists because a miss here is silent: the viewer falls',
    ' *  back to auto-fit and simply looks worse, with nothing logged. */',
    'export function overviewFor(map: string): (typeof OVERVIEWS)[string] | null {',
    '  const key = map.toLowerCase();',
    '  if (OVERVIEWS[key]) return OVERVIEWS[key];',
    "  const swapped = key.startsWith('l4d_vs_')",
    "    ? key.replace('l4d_vs_', 'l4d_')",
    "    : key.replace('l4d_', 'l4d_vs_');",
    '  return OVERVIEWS[swapped] ?? null;',
    '}',
    '',
]

with open(out, 'w') as fh:
    fh.write('\n'.join(lines))
print(f'wrote {out}: {len(maps)} maps, {sum(len(l) for _, l in maps)} layers')
