import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { DB } from './db.js';
import type { BalanceKnobs } from './balanceKnobs.js';
import { transportFor, type AddonsTransport } from './addonsTransport.js';
import { getServer, listServers, type ServerRow } from './serverPool.js';
import { publishAdminEvent } from './adminFeed.js';

/**
 * The balance watch list as a file on every box, which pug-match 0.3.14+
 * reads at map start instead of its compiled list, so watching one more value
 * is a site-only change. See
 * docs/superpowers/specs/2026-09-24-balance-watch-file-design.md.
 */

export const WATCH_FILE = 'pug_balance_watch.txt';
const SWEEP_MS = 60_000;
const TIMEOUT_MS = 60_000;
/** A box whose file was read back equal is not read again for this long. */
const REVERIFY_MS = 6 * 3_600_000;

export function renderWatchFile(k: BalanceKnobs): string {
  return [
    '// GENERATED by the site from balance/knobs.json. Do not edit: it is rewritten.',
    '// Read by pug-match at map start. One entry per line: cvar <name> | file <path>',
    '// | dir <path> <ext> | weapon <classname> <key>.',
    ...k.cvars.map((c) => `cvar ${c.cvar}`),
    ...k.files.map((f) => `file ${f.path}`),
    ...k.dirs.map((d) => `dir ${d.path} ${d.ext}`),
    ...(k.weapons ?? []).map((w) => `weapon ${w.weapon} ${w.key}`),
    '',
  ].join('\n');
}

/** `<game>/left4dead/addons` -> `<game>/left4dead/addons/sourcemod/data`. */
export function dataDirOf(server: ServerRow): string | null {
  const dir = (server as ServerRow & { addons_dir?: string | null }).addons_dir;
  if (!dir || !/\/addons\/?$/.test(dir)) return null;
  return `${dir.replace(/\/$/, '')}/sourcemod/data`;
}

export interface WatchOutcome { serverId: number; server: string; ok: boolean; wrote?: boolean; skipped?: string; error?: string }

const sha = (s: string) => createHash('sha256').update(s).digest('hex');

export class BalanceWatchWriter {
  private chain: Promise<unknown> = Promise.resolve();
  private timer: ReturnType<typeof setInterval> | null = null;
  /** serverId -> content hash and when it was last read back equal. */
  private verified = new Map<number, { hash: string; at: number }>();
  /** Servers already reported as failing, so a box that keeps failing posts once. */
  private reported = new Set<number>();

  constructor(private deps: {
    db: DB;
    /** The file to put on every box, or null when knobs.json failed to load. */
    content: () => string | null;
    transport?: (s: ServerRow, dir: string) => AddonsTransport | null;
    intervalMs?: number;
    timeoutMs?: number;
    now?: () => number;
  }) {}

  private now() { return (this.deps.now ?? Date.now)(); }

  private queue<T>(fn: () => Promise<T>, fallback: T): Promise<T> {
    const next = this.chain.then(fn).catch((err) => {
      console.error('[balanceWatch] pass failed:', err);
      return fallback;
    });
    this.chain = next;
    return next;
  }

  sync(): Promise<WatchOutcome[]> {
    return this.queue(async () => {
      const out: WatchOutcome[] = [];
      if (this.deps.content() === null) return out;
      for (const s of listServers(this.deps.db).filter((x) => x.enabled === 1)) {
        const fresh = getServer(this.deps.db, s.id);
        if (!fresh || fresh.status !== 'idle') { out.push({ serverId: s.id, server: s.name, ok: false, skipped: 'busy' }); continue; }
        const r = await this.writeOne(fresh);
        if (r) out.push(r);
      }
      return out;
    }, []);
  }

  /** Never rejects: runs in front of the after-match restart, so the new list
   *  is read at the box's next map. */
  async writeForRelease(serverId: number): Promise<void> {
    await this.queue(async () => {
      const s = getServer(this.deps.db, serverId);
      if (!s || s.enabled !== 1 || (s.status !== 'idle' && s.status !== 'offline')) return;
      await this.writeOne(s);
    }, undefined);
  }

  private bounded<T>(p: Promise<T>): Promise<T> {
    const ms = this.deps.timeoutMs ?? TIMEOUT_MS;
    let t: ReturnType<typeof setTimeout> | undefined;
    const timeout = new Promise<never>((_, reject) => { t = setTimeout(() => reject(new Error(`timed out after ${ms} ms`)), ms); });
    return Promise.race([p, timeout]).finally(() => clearTimeout(t));
  }

  /** Null when there is nothing to do for this box. */
  private async writeOne(server: ServerRow): Promise<WatchOutcome | null> {
    const content = this.deps.content();
    if (content === null) return null;
    const hash = sha(content);
    const v = this.verified.get(server.id);
    if (v && v.hash === hash && this.now() - v.at < REVERIFY_MS) return { serverId: server.id, server: server.name, ok: true, wrote: false };
    const dir = dataDirOf(server);
    const t = dir ? (this.deps.transport ?? transportFor)(server, dir) : null;
    if (!t) return null; // no transport: nothing the site can do for this box
    const base = { serverId: server.id, server: server.name };
    let tmp: string | null = null;
    try {
      const current = await this.bounded(t.readText(WATCH_FILE));
      let wrote = false;
      if (current !== content) {
        tmp = await mkdtemp(join(tmpdir(), 'pug-watch-'));
        await writeFile(join(tmp, WATCH_FILE), content, 'utf8');
        await this.bounded(t.put(join(tmp, WATCH_FILE), WATCH_FILE));
        const back = await this.bounded(t.readText(WATCH_FILE));
        if (back !== content) throw new Error('read-back differs from what was written');
        wrote = true;
      }
      this.verified.set(server.id, { hash, at: this.now() });
      this.reported.delete(server.id);
      return { ...base, ok: true, wrote };
    } catch (err) {
      const error = err instanceof Error ? err.message : String(err);
      console.error(`[balanceWatch] ${server.name}: ${error}`);
      if (!this.reported.has(server.id)) {
        this.reported.add(server.id);
        publishAdminEvent({ kind: 'problem', text: `Could not write the balance watch list to ${server.name}: ${error}. Retried every minute.` });
      }
      return { ...base, ok: false, error };
    } finally {
      if (tmp) void rm(tmp, { recursive: true, force: true }).catch(() => {});
    }
  }

  start(): void {
    if (this.timer) return;
    this.timer = setInterval(() => void this.sync(), this.deps.intervalMs ?? SWEEP_MS);
    this.timer.unref();
  }

  stop(): void {
    if (this.timer) clearInterval(this.timer);
    this.timer = null;
  }
}
