import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export interface BalanceKnobs {
  cvars: { cvar: string; label: string; group: string; min?: number; max?: number }[];
  files: { path: string; label: string }[];
  dirs: { path: string; ext: string; label: string }[];
  versionless: string[];
  /** Plugins that are not balance at all and get loaded and unloaded around a
   *  match, so their presence is noise. Dropped from the inventory entirely. */
  ignored?: string[];
}

export const BALANCE_KNOBS_PATH = fileURLToPath(new URL('../balance/knobs.json', import.meta.url));

const CVAR_RE = /^[a-z0-9_]{1,63}$/;
// Relative, forward slashes, no spaces, no parent traversal.
const PATH_RE = /^(?!\/)(?!.*\.\.)[A-Za-z0-9_\-./]{1,200}$/;

/** Load and validate the watched list. `raw` lets tests validate an object
 *  without touching the disk. Throws on anything the plugin could not use. */
export function loadBalanceKnobs(path: string = BALANCE_KNOBS_PATH, raw?: unknown): BalanceKnobs {
  const k = (raw ?? JSON.parse(readFileSync(path, 'utf8'))) as BalanceKnobs;
  if (!Array.isArray(k.cvars)) throw new Error('balance knobs: cvars must be an array');
  if (!Array.isArray(k.files)) throw new Error('balance knobs: files must be an array');
  if (!Array.isArray(k.dirs)) throw new Error('balance knobs: dirs must be an array');
  if (!Array.isArray(k.versionless)) throw new Error('balance knobs: versionless must be an array');
  if (k.ignored !== undefined && !Array.isArray(k.ignored)) throw new Error('balance knobs: ignored must be an array');
  for (const c of k.cvars) if (!CVAR_RE.test(c.cvar)) throw new Error(`bad cvar name: ${c.cvar}`);
  for (const f of k.files) if (!PATH_RE.test(f.path)) throw new Error(`bad file path: ${f.path}`);
  for (const d of k.dirs) {
    if (!PATH_RE.test(d.path)) throw new Error(`bad dir path: ${d.path}`);
    if (!/^\.[a-z0-9]{1,8}$/.test(d.ext)) throw new Error(`bad dir ext: ${d.ext}`);
  }
  if (new Set(k.cvars.map((c) => c.cvar)).size !== k.cvars.length) throw new Error('duplicate cvar');
  return k;
}

/** The plugin include. Deterministic, so the parity test can compare bytes. */
export function renderBalanceListInc(k: BalanceKnobs): string {
  // Not `static`: SourcePawn's compiler scopes a file-static global to the
  // physical file that declares it, even when that file is spliced in by
  // #include, so pug-balance.inc (a different physical file) could not see
  // these arrays at all ("undefined symbol") with `static` here. Not `const`
  // either: `const char name[][] = {...}` at global scope fails to parse on
  // this compiler ("expected token: '=', but found '['"); a plain global
  // array declaration compiles and is just as read-only in practice, since
  // nothing ever writes to it.
  const arr = (name: string, items: string[]) =>
    `char ${name}[][] = {\n${items.map((s) => `\t"${s}"`).join(',\n')}\n};\n`;
  return [
    '// GENERATED by scripts/gen-balance-list.ts from balance/knobs.json. Do not edit.',
    '// tests/balanceKnobs.test.ts fails when this file and knobs.json disagree.',
    '',
    arr('g_sBalCvars', k.cvars.map((c) => c.cvar)),
    arr('g_sBalFiles', k.files.map((f) => f.path)),
    arr('g_sBalDirs', k.dirs.map((d) => d.path)),
    arr('g_sBalDirExt', k.dirs.map((d) => d.ext)),
  ].join('\n');
}
