import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * The committed list of files the game server forces for consistency checking,
 * as the web needs it: to refuse a campaign VPK that ships one of those paths.
 *
 * A forced path that a campaign legitimately overrides would disconnect every
 * player on that map, stock client or not, because the client compares its own
 * disk against the SERVER's checksum and the server has the campaign mounted.
 *
 * The file is the same one the plugin reads, generated by
 * scripts/gen-consistency-list.ts. It is read from the repo checkout, relative
 * to this module, which is also where it is on the box: deploy-web.sh rsyncs
 * the whole tree to /home/pug/app and the service runs `tsx src/index.ts`.
 */
export const CONSISTENCY_CFG = join(
  dirname(fileURLToPath(import.meta.url)), '..', 'consistency', 'configs', 'l4d_consistency.cfg',
);

/** One path per line; blank lines and `#` comments (group headers included)
 *  are skipped. Paths keep the spelling the file has. */
export function parseConsistencyList(text: string): string[] {
  return text.split('\n').map((l) => l.trim()).filter((l) => l !== '' && !l.startsWith('#'));
}

/**
 * The list, or null when it cannot be trusted: the file is missing, unreadable,
 * or holds no paths at all. Null is loud here and makes the uploader refuse
 * everything, because the alternative is an uploader that silently checks
 * nothing, and the first anyone would hear of it is a full server dropping to
 * the menu on map three.
 */
export function loadConsistencyList(path: string = CONSISTENCY_CFG): string[] | null {
  let text: string;
  try {
    text = readFileSync(path, 'utf8');
  } catch (err) {
    console.error(`[consistency] cannot read the enforced file list at ${path}; campaign uploads will be refused:`, err);
    return null;
  }
  const paths = parseConsistencyList(text);
  if (paths.length === 0) {
    console.error(`[consistency] the enforced file list at ${path} holds no paths; campaign uploads will be refused`);
    return null;
  }
  return paths;
}

const norm = (p: string): string => p.replace(/\\/g, '/').toLowerCase();

/** The forced paths a VPK also ships, compared case-insensitively (the engine's
 *  file system is, and addon authors are careless about case), in list order
 *  and in the list's spelling. */
export function consistencyCollisions(vpkPaths: string[], forced: string[]): string[] {
  const shipped = new Set(vpkPaths.map(norm));
  return forced.filter((p) => shipped.has(norm(p)));
}

/** The sentence an admin sees. Names every path up to ten, then a count. */
export function collisionMessage(collisions: string[]): string {
  const shown = collisions.slice(0, 10).join(', ');
  const more = collisions.length > 10 ? `, and ${collisions.length - 10} more` : '';
  return `this VPK replaces ${collisions.length === 1 ? 'a file' : 'files'} the server enforces for consistency, `
    + `which would disconnect every player on its maps: ${shown}${more}. `
    + 'Remove them from the VPK and upload it again.';
}
