/**
 * Map overview layers, generated by tools/gen-overviews.py.
 *
 * Do not edit by hand. Every number here is read back from the engine at
 * capture time, so a typo puts every avatar on that map in the wrong place
 * and nothing reports an error.
 *
 * Each map is a stack of horizontal slices cut at different camera heights,
 * ascending. A layer shows everything below its cut height and nothing above,
 * so the right one to draw is the lowest whose cut is still above the players.
 * All layers of a map share one transform, so switching between them needs no
 * repositioning.
 *
 * This module has no imports, deliberately: it is loaded by the browser as
 * well as the server. See src/mapTransform.ts for the matching named types.
 */

export const OVERVIEWS: Record<string, {
  map: string;
  layers: {
    image: string;
    cutHeight: number;
    unitsPerPixel: number;
    originX: number;
    originY: number;
    width: number;
    height: number;
  }[];
}> = {
  'l4d_garage01_alleys': {
    map: 'l4d_garage01_alleys',
    layers: [
      { image: '/overviews/l4d_garage01_alleys_z-0186.webp', cutHeight: -186, unitsPerPixel: 11.279308, originX: -16747, originY: 1246, width: 2048, height: 1271 },
      { image: '/overviews/l4d_garage01_alleys_z+0070.webp', cutHeight: 70, unitsPerPixel: 11.279308, originX: -16747, originY: 1246, width: 2048, height: 1271 },
      { image: '/overviews/l4d_garage01_alleys_z+0326.webp', cutHeight: 326, unitsPerPixel: 11.279308, originX: -16747, originY: 1246, width: 2048, height: 1271 },
      { image: '/overviews/l4d_garage01_alleys_z+0894.webp', cutHeight: 894, unitsPerPixel: 11.279308, originX: -16747, originY: 1246, width: 2048, height: 1271 },
      { image: '/overviews/l4d_garage01_alleys_z+0990.webp', cutHeight: 990, unitsPerPixel: 11.279308, originX: -16747, originY: 1246, width: 2048, height: 1271 },
    ],
  },
  'l4d_garage02_lots': {
    map: 'l4d_garage02_lots',
    layers: [
      { image: '/overviews/l4d_garage02_lots_z-0154.webp', cutHeight: -154, unitsPerPixel: 8.056648, originX: -4243, originY: 8128, width: 2048, height: 1271 },
      { image: '/overviews/l4d_garage02_lots_z+0134.webp', cutHeight: 134, unitsPerPixel: 8.056648, originX: -4243, originY: 8128, width: 2048, height: 1271 },
      { image: '/overviews/l4d_garage02_lots_z+0518.webp', cutHeight: 518, unitsPerPixel: 8.056648, originX: -4243, originY: 8128, width: 2048, height: 1271 },
      { image: '/overviews/l4d_garage02_lots_z+1086.webp', cutHeight: 1086, unitsPerPixel: 8.056648, originX: -4243, originY: 8128, width: 2048, height: 1271 },
      { image: '/overviews/l4d_garage02_lots_z+1214.webp', cutHeight: 1214, unitsPerPixel: 8.056648, originX: -4243, originY: 8128, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_airport01_greenhouse': {
    map: 'l4d_vs_airport01_greenhouse',
    layers: [
      { image: '/overviews/l4d_vs_airport01_greenhouse_z+0102.webp', cutHeight: 102, unitsPerPixel: 6.445319, originX: -1973, originY: 5791, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport01_greenhouse_z+0262.webp', cutHeight: 262, unitsPerPixel: 6.445319, originX: -1973, originY: 5791, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport01_greenhouse_z+0518.webp', cutHeight: 518, unitsPerPixel: 6.445319, originX: -1973, originY: 5791, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport01_greenhouse_z+0774.webp', cutHeight: 774, unitsPerPixel: 6.445319, originX: -1973, originY: 5791, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport01_greenhouse_z+1030.webp', cutHeight: 1030, unitsPerPixel: 6.445319, originX: -1973, originY: 5791, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport01_greenhouse_z+1598.webp', cutHeight: 1598, unitsPerPixel: 6.445319, originX: -1973, originY: 5791, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport01_greenhouse_z+1806.webp', cutHeight: 1806, unitsPerPixel: 6.445319, originX: -1973, originY: 5791, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_airport02_offices': {
    map: 'l4d_vs_airport02_offices',
    layers: [
      { image: '/overviews/l4d_vs_airport02_offices_z+0070.webp', cutHeight: 70, unitsPerPixel: 5.639654, originX: 1328, originY: 7842, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport02_offices_z+0198.webp', cutHeight: 198, unitsPerPixel: 5.639654, originX: 1328, originY: 7842, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport02_offices_z+0326.webp', cutHeight: 326, unitsPerPixel: 5.639654, originX: 1328, originY: 7842, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport02_offices_z+0454.webp', cutHeight: 454, unitsPerPixel: 5.639654, originX: 1328, originY: 7842, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport02_offices_z+0582.webp', cutHeight: 582, unitsPerPixel: 5.639654, originX: 1328, originY: 7842, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport02_offices_z+0710.webp', cutHeight: 710, unitsPerPixel: 5.639654, originX: 1328, originY: 7842, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport02_offices_z+0838.webp', cutHeight: 838, unitsPerPixel: 5.639654, originX: 1328, originY: 7842, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport02_offices_z+0966.webp', cutHeight: 966, unitsPerPixel: 5.639654, originX: 1328, originY: 7842, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport02_offices_z+1150.webp', cutHeight: 1150, unitsPerPixel: 5.639654, originX: 1328, originY: 7842, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport02_offices_z+1534.webp', cutHeight: 1534, unitsPerPixel: 5.639654, originX: 1328, originY: 7842, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport02_offices_z+2030.webp', cutHeight: 2030, unitsPerPixel: 5.639654, originX: 1328, originY: 7842, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_airport03_garage': {
    map: 'l4d_vs_airport03_garage',
    layers: [
      { image: '/overviews/l4d_vs_airport03_garage_z+0070.webp', cutHeight: 70, unitsPerPixel: 9.265146, originX: -13116, originY: 6425, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport03_garage_z+0326.webp', cutHeight: 326, unitsPerPixel: 9.265146, originX: -13116, originY: 6425, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport03_garage_z+0582.webp', cutHeight: 582, unitsPerPixel: 9.265146, originX: -13116, originY: 6425, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport03_garage_z+1150.webp', cutHeight: 1150, unitsPerPixel: 9.265146, originX: -13116, originY: 6425, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport03_garage_z+1934.webp', cutHeight: 1934, unitsPerPixel: 9.265146, originX: -13116, originY: 6425, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_airport04_terminal': {
    map: 'l4d_vs_airport04_terminal',
    layers: [
      { image: '/overviews/l4d_vs_airport04_terminal_z+0070.webp', cutHeight: 70, unitsPerPixel: 5.236821, originX: -3491, originY: 6467, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport04_terminal_z+0198.webp', cutHeight: 198, unitsPerPixel: 5.236821, originX: -3491, originY: 6467, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport04_terminal_z+0326.webp', cutHeight: 326, unitsPerPixel: 5.236821, originX: -3491, originY: 6467, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport04_terminal_z+0454.webp', cutHeight: 454, unitsPerPixel: 5.236821, originX: -3491, originY: 6467, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport04_terminal_z+0582.webp', cutHeight: 582, unitsPerPixel: 5.236821, originX: -3491, originY: 6467, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport04_terminal_z+0766.webp', cutHeight: 766, unitsPerPixel: 5.236821, originX: -3491, originY: 6467, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport04_terminal_z+1150.webp', cutHeight: 1150, unitsPerPixel: 5.236821, originX: -3491, originY: 6467, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport04_terminal_z+4030.webp', cutHeight: 4030, unitsPerPixel: 5.236821, originX: -3491, originY: 6467, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_airport05_runway': {
    map: 'l4d_vs_airport05_runway',
    layers: [
      { image: '/overviews/l4d_vs_airport05_runway_z-0378.webp', cutHeight: -378, unitsPerPixel: 12.487805, originX: -13298, originY: 17864, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport05_runway_z-0122.webp', cutHeight: -122, unitsPerPixel: 12.487805, originX: -13298, originY: 17864, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport05_runway_z+0134.webp', cutHeight: 134, unitsPerPixel: 12.487805, originX: -13298, originY: 17864, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport05_runway_z+0390.webp', cutHeight: 390, unitsPerPixel: 12.487805, originX: -13298, originY: 17864, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport05_runway_z+0958.webp', cutHeight: 958, unitsPerPixel: 12.487805, originX: -13298, originY: 17864, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_airport05_runway_z+8158.webp', cutHeight: 8158, unitsPerPixel: 12.487805, originX: -13298, originY: 17864, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_farm01_hilltop': {
    map: 'l4d_vs_farm01_hilltop',
    layers: [
      { image: '/overviews/l4d_vs_farm01_hilltop_z+0326.webp', cutHeight: 326, unitsPerPixel: 7.250983, originX: -16547, originY: -6299, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm01_hilltop_z+0582.webp', cutHeight: 582, unitsPerPixel: 7.250983, originX: -16547, originY: -6299, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm01_hilltop_z+0838.webp', cutHeight: 838, unitsPerPixel: 7.250983, originX: -16547, originY: -6299, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm01_hilltop_z+1406.webp', cutHeight: 1406, unitsPerPixel: 7.250983, originX: -16547, originY: -6299, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm01_hilltop_z+2270.webp', cutHeight: 2270, unitsPerPixel: 7.250983, originX: -16547, originY: -6299, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_farm02_traintunnel': {
    map: 'l4d_vs_farm02_traintunnel',
    layers: [
      { image: '/overviews/l4d_vs_farm02_traintunnel_z+0006.webp', cutHeight: 6, unitsPerPixel: 6.848151, originX: -11939, originY: -4779, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm02_traintunnel_z+0134.webp', cutHeight: 134, unitsPerPixel: 6.848151, originX: -11939, originY: -4779, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm02_traintunnel_z+0262.webp', cutHeight: 262, unitsPerPixel: 6.848151, originX: -11939, originY: -4779, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm02_traintunnel_z+0390.webp', cutHeight: 390, unitsPerPixel: 6.848151, originX: -11939, originY: -4779, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm02_traintunnel_z+0518.webp', cutHeight: 518, unitsPerPixel: 6.848151, originX: -11939, originY: -4779, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm02_traintunnel_z+0646.webp', cutHeight: 646, unitsPerPixel: 6.848151, originX: -11939, originY: -4779, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm02_traintunnel_z+0830.webp', cutHeight: 830, unitsPerPixel: 6.848151, originX: -11939, originY: -4779, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm02_traintunnel_z+1214.webp', cutHeight: 1214, unitsPerPixel: 6.848151, originX: -11939, originY: -4779, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm02_traintunnel_z+2270.webp', cutHeight: 2270, unitsPerPixel: 6.848151, originX: -11939, originY: -4779, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_farm03_bridge': {
    map: 'l4d_vs_farm03_bridge',
    layers: [
      { image: '/overviews/l4d_vs_farm03_bridge_z+0134.webp', cutHeight: 134, unitsPerPixel: 8.056648, originX: -3483, originY: -8921, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm03_bridge_z+0390.webp', cutHeight: 390, unitsPerPixel: 8.056648, originX: -3483, originY: -8921, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm03_bridge_z+0646.webp', cutHeight: 646, unitsPerPixel: 8.056648, originX: -3483, originY: -8921, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm03_bridge_z+1214.webp', cutHeight: 1214, unitsPerPixel: 8.056648, originX: -3483, originY: -8921, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm03_bridge_z+1806.webp', cutHeight: 1806, unitsPerPixel: 8.056648, originX: -3483, originY: -8921, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_farm04_barn': {
    map: 'l4d_vs_farm04_barn',
    layers: [
      { image: '/overviews/l4d_vs_farm04_barn_z-0058.webp', cutHeight: -58, unitsPerPixel: 8.862313, originX: 3250, originY: -241, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm04_barn_z+0070.webp', cutHeight: 70, unitsPerPixel: 8.862313, originX: 3250, originY: -241, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm04_barn_z+0198.webp', cutHeight: 198, unitsPerPixel: 8.862313, originX: 3250, originY: -241, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm04_barn_z+0326.webp', cutHeight: 326, unitsPerPixel: 8.862313, originX: 3250, originY: -241, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm04_barn_z+0454.webp', cutHeight: 454, unitsPerPixel: 8.862313, originX: 3250, originY: -241, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm04_barn_z+0582.webp', cutHeight: 582, unitsPerPixel: 8.862313, originX: 3250, originY: -241, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm04_barn_z+0710.webp', cutHeight: 710, unitsPerPixel: 8.862313, originX: 3250, originY: -241, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm04_barn_z+0894.webp', cutHeight: 894, unitsPerPixel: 8.862313, originX: 3250, originY: -241, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm04_barn_z+1278.webp', cutHeight: 1278, unitsPerPixel: 8.862313, originX: 3250, originY: -241, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm04_barn_z+2286.webp', cutHeight: 2286, unitsPerPixel: 8.862313, originX: 3250, originY: -241, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_farm05_cornfield': {
    map: 'l4d_vs_farm05_cornfield',
    layers: [
      { image: '/overviews/l4d_vs_farm05_cornfield_z+0198.webp', cutHeight: 198, unitsPerPixel: 4.833989, originX: 3891, originY: 4893, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm05_cornfield_z+0454.webp', cutHeight: 454, unitsPerPixel: 4.833989, originX: 3891, originY: 4893, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm05_cornfield_z+0710.webp', cutHeight: 710, unitsPerPixel: 4.833989, originX: 3891, originY: 4893, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm05_cornfield_z+1278.webp', cutHeight: 1278, unitsPerPixel: 4.833989, originX: 3891, originY: 4893, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_farm05_cornfield_z+1934.webp', cutHeight: 1934, unitsPerPixel: 4.833989, originX: 3891, originY: 4893, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_hospital01_apartment': {
    map: 'l4d_vs_hospital01_apartment',
    layers: [
      { image: '/overviews/l4d_vs_hospital01_apartment_z-0177.webp', cutHeight: -177, unitsPerPixel: 5.639654, originX: -2067, originY: 6609, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital01_apartment_z-0114.webp', cutHeight: -114, unitsPerPixel: 5.639654, originX: -2067, originY: 6609, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital01_apartment_z+0014.webp', cutHeight: 14, unitsPerPixel: 5.639654, originX: -2067, originY: 6609, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital01_apartment_z+0142.webp', cutHeight: 142, unitsPerPixel: 5.639654, originX: -2067, originY: 6609, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital01_apartment_z+0270.webp', cutHeight: 270, unitsPerPixel: 5.639654, originX: -2067, originY: 6609, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital01_apartment_z+0398.webp', cutHeight: 398, unitsPerPixel: 5.639654, originX: -2067, originY: 6609, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital01_apartment_z+0526.webp', cutHeight: 526, unitsPerPixel: 5.639654, originX: -2067, originY: 6609, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital01_apartment_z+0654.webp', cutHeight: 654, unitsPerPixel: 5.639654, originX: -2067, originY: 6609, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital01_apartment_z+0782.webp', cutHeight: 782, unitsPerPixel: 5.639654, originX: -2067, originY: 6609, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital01_apartment_z+0910.webp', cutHeight: 910, unitsPerPixel: 5.639654, originX: -2067, originY: 6609, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital01_apartment_z+1038.webp', cutHeight: 1038, unitsPerPixel: 5.639654, originX: -2067, originY: 6609, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital01_apartment_z+1166.webp', cutHeight: 1166, unitsPerPixel: 5.639654, originX: -2067, originY: 6609, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital01_apartment_z+1294.webp', cutHeight: 1294, unitsPerPixel: 5.639654, originX: -2067, originY: 6609, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital01_apartment_z+4558.webp', cutHeight: 4558, unitsPerPixel: 5.639654, originX: -2067, originY: 6609, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_hospital02_subway': {
    map: 'l4d_vs_hospital02_subway',
    layers: [
      { image: '/overviews/l4d_vs_hospital02_subway_z-0438.webp', cutHeight: -438, unitsPerPixel: 7.653816, originX: -977, originY: 9796, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital02_subway_z-0386.webp', cutHeight: -386, unitsPerPixel: 7.653816, originX: -977, originY: 9796, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital02_subway_z-0258.webp', cutHeight: -258, unitsPerPixel: 7.653816, originX: -977, originY: 9796, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital02_subway_z-0130.webp', cutHeight: -130, unitsPerPixel: 7.653816, originX: -977, originY: 9796, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital02_subway_z-0002.webp', cutHeight: -2, unitsPerPixel: 7.653816, originX: -977, originY: 9796, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital02_subway_z+0126.webp', cutHeight: 126, unitsPerPixel: 7.653816, originX: -977, originY: 9796, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital02_subway_z+0254.webp', cutHeight: 254, unitsPerPixel: 7.653816, originX: -977, originY: 9796, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital02_subway_z+0382.webp', cutHeight: 382, unitsPerPixel: 7.653816, originX: -977, originY: 9796, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital02_subway_z+0510.webp', cutHeight: 510, unitsPerPixel: 7.653816, originX: -977, originY: 9796, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital02_subway_z+0638.webp', cutHeight: 638, unitsPerPixel: 7.653816, originX: -977, originY: 9796, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital02_subway_z+0766.webp', cutHeight: 766, unitsPerPixel: 7.653816, originX: -977, originY: 9796, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital02_subway_z+0894.webp', cutHeight: 894, unitsPerPixel: 7.653816, originX: -977, originY: 9796, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital02_subway_z+1886.webp', cutHeight: 1886, unitsPerPixel: 7.653816, originX: -977, originY: 9796, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_hospital03_sewers': {
    map: 'l4d_vs_hospital03_sewers',
    layers: [
      { image: '/overviews/l4d_vs_hospital03_sewers_z-0412.webp', cutHeight: -412, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital03_sewers_z-0364.webp', cutHeight: -364, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital03_sewers_z-0236.webp', cutHeight: -236, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital03_sewers_z-0108.webp', cutHeight: -108, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital03_sewers_z+0020.webp', cutHeight: 20, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital03_sewers_z+0148.webp', cutHeight: 148, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital03_sewers_z+0276.webp', cutHeight: 276, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital03_sewers_z+0404.webp', cutHeight: 404, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital03_sewers_z+0532.webp', cutHeight: 532, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital03_sewers_z+0660.webp', cutHeight: 660, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital03_sewers_z+0788.webp', cutHeight: 788, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital03_sewers_z+0916.webp', cutHeight: 916, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital03_sewers_z+1044.webp', cutHeight: 1044, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital03_sewers_z+1172.webp', cutHeight: 1172, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital03_sewers_z+6062.webp', cutHeight: 6062, unitsPerPixel: 8.056648, originX: 3924, originY: 14137, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_hospital04_interior': {
    map: 'l4d_vs_hospital04_interior',
    layers: [
      { image: '/overviews/l4d_vs_hospital04_interior_z+0070.webp', cutHeight: 70, unitsPerPixel: 3.222659, originX: 9285, originY: 15693, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital04_interior_z+0198.webp', cutHeight: 198, unitsPerPixel: 3.222659, originX: 9285, originY: 15693, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital04_interior_z+0326.webp', cutHeight: 326, unitsPerPixel: 3.222659, originX: 9285, originY: 15693, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital04_interior_z+0454.webp', cutHeight: 454, unitsPerPixel: 3.222659, originX: 9285, originY: 15693, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital04_interior_z+0582.webp', cutHeight: 582, unitsPerPixel: 3.222659, originX: 9285, originY: 15693, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital04_interior_z+0710.webp', cutHeight: 710, unitsPerPixel: 3.222659, originX: 9285, originY: 15693, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital04_interior_z+0894.webp', cutHeight: 894, unitsPerPixel: 3.222659, originX: 9285, originY: 15693, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital04_interior_z+1278.webp', cutHeight: 1278, unitsPerPixel: 3.222659, originX: 9285, originY: 15693, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital04_interior_z+5574.webp', cutHeight: 5574, unitsPerPixel: 3.222659, originX: 9285, originY: 15693, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital04_interior_z+5702.webp', cutHeight: 5702, unitsPerPixel: 3.222659, originX: 9285, originY: 15693, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital04_interior_z+5830.webp', cutHeight: 5830, unitsPerPixel: 3.222659, originX: 9285, originY: 15693, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital04_interior_z+6014.webp', cutHeight: 6014, unitsPerPixel: 3.222659, originX: 9285, originY: 15693, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital04_interior_z+6398.webp', cutHeight: 6398, unitsPerPixel: 3.222659, originX: 9285, originY: 15693, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital04_interior_z+7646.webp', cutHeight: 7646, unitsPerPixel: 3.222659, originX: 9285, originY: 15693, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_hospital05_rooftop': {
    map: 'l4d_vs_hospital05_rooftop',
    layers: [
      { image: '/overviews/l4d_vs_hospital05_rooftop_z+0262.webp', cutHeight: 262, unitsPerPixel: 2.819827, originX: 3648, originY: 9768, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital05_rooftop_z+0446.webp', cutHeight: 446, unitsPerPixel: 2.819827, originX: 3648, originY: 9768, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital05_rooftop_z+0830.webp', cutHeight: 830, unitsPerPixel: 2.819827, originX: 3648, originY: 9768, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital05_rooftop_z+5574.webp', cutHeight: 5574, unitsPerPixel: 2.819827, originX: 3648, originY: 9768, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital05_rooftop_z+5702.webp', cutHeight: 5702, unitsPerPixel: 2.819827, originX: 3648, originY: 9768, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital05_rooftop_z+5830.webp', cutHeight: 5830, unitsPerPixel: 2.819827, originX: 3648, originY: 9768, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital05_rooftop_z+5958.webp', cutHeight: 5958, unitsPerPixel: 2.819827, originX: 3648, originY: 9768, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital05_rooftop_z+6086.webp', cutHeight: 6086, unitsPerPixel: 2.819827, originX: 3648, originY: 9768, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital05_rooftop_z+6214.webp', cutHeight: 6214, unitsPerPixel: 2.819827, originX: 3648, originY: 9768, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital05_rooftop_z+6342.webp', cutHeight: 6342, unitsPerPixel: 2.819827, originX: 3648, originY: 9768, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital05_rooftop_z+6526.webp', cutHeight: 6526, unitsPerPixel: 2.819827, originX: 3648, originY: 9768, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital05_rooftop_z+6910.webp', cutHeight: 6910, unitsPerPixel: 2.819827, originX: 3648, originY: 9768, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_hospital05_rooftop_z+8158.webp', cutHeight: 8158, unitsPerPixel: 2.819827, originX: 3648, originY: 9768, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_smalltown01_caves': {
    map: 'l4d_vs_smalltown01_caves',
    layers: [
      { image: '/overviews/l4d_vs_smalltown01_caves_z-0314.webp', cutHeight: -314, unitsPerPixel: 9.667978, originX: -21215, originY: -3809, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown01_caves_z-0058.webp', cutHeight: -58, unitsPerPixel: 9.667978, originX: -21215, originY: -3809, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown01_caves_z+0198.webp', cutHeight: 198, unitsPerPixel: 9.667978, originX: -21215, originY: -3809, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown01_caves_z+0454.webp', cutHeight: 454, unitsPerPixel: 9.667978, originX: -21215, originY: -3809, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown01_caves_z+0710.webp', cutHeight: 710, unitsPerPixel: 9.667978, originX: -21215, originY: -3809, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown01_caves_z+1278.webp', cutHeight: 1278, unitsPerPixel: 9.667978, originX: -21215, originY: -3809, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown01_caves_z+1566.webp', cutHeight: 1566, unitsPerPixel: 9.667978, originX: -21215, originY: -3809, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_smalltown02_drainage': {
    map: 'l4d_vs_smalltown02_drainage',
    layers: [
      { image: '/overviews/l4d_vs_smalltown02_drainage_z-0634.webp', cutHeight: -634, unitsPerPixel: 4.833989, originX: -13662, originY: -3090, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown02_drainage_z-0506.webp', cutHeight: -506, unitsPerPixel: 4.833989, originX: -13662, originY: -3090, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown02_drainage_z-0378.webp', cutHeight: -378, unitsPerPixel: 4.833989, originX: -13662, originY: -3090, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown02_drainage_z-0250.webp', cutHeight: -250, unitsPerPixel: 4.833989, originX: -13662, originY: -3090, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown02_drainage_z-0122.webp', cutHeight: -122, unitsPerPixel: 4.833989, originX: -13662, originY: -3090, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown02_drainage_z+0006.webp', cutHeight: 6, unitsPerPixel: 4.833989, originX: -13662, originY: -3090, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown02_drainage_z+0134.webp', cutHeight: 134, unitsPerPixel: 4.833989, originX: -13662, originY: -3090, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown02_drainage_z+0262.webp', cutHeight: 262, unitsPerPixel: 4.833989, originX: -13662, originY: -3090, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown02_drainage_z+0446.webp', cutHeight: 446, unitsPerPixel: 4.833989, originX: -13662, originY: -3090, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown02_drainage_z+0830.webp', cutHeight: 830, unitsPerPixel: 4.833989, originX: -13662, originY: -3090, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown02_drainage_z+1380.webp', cutHeight: 1380, unitsPerPixel: 4.833989, originX: -13662, originY: -3090, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_smalltown03_ranchhouse': {
    map: 'l4d_vs_smalltown03_ranchhouse',
    layers: [
      { image: '/overviews/l4d_vs_smalltown03_ranchhouse_z+0038.webp', cutHeight: 38, unitsPerPixel: 8.459481, originX: -16206, originY: 2506, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown03_ranchhouse_z+0262.webp', cutHeight: 262, unitsPerPixel: 8.459481, originX: -16206, originY: 2506, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown03_ranchhouse_z+0646.webp', cutHeight: 646, unitsPerPixel: 8.459481, originX: -16206, originY: 2506, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown03_ranchhouse_z+1214.webp', cutHeight: 1214, unitsPerPixel: 8.459481, originX: -16206, originY: 2506, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown03_ranchhouse_z+1902.webp', cutHeight: 1902, unitsPerPixel: 8.459481, originX: -16206, originY: 2506, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_smalltown04_mainstreet': {
    map: 'l4d_vs_smalltown04_mainstreet',
    layers: [
      { image: '/overviews/l4d_vs_smalltown04_mainstreet_z-0026.webp', cutHeight: -26, unitsPerPixel: 8.056648, originX: -9030, originY: 1620, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown04_mainstreet_z+0198.webp', cutHeight: 198, unitsPerPixel: 8.056648, originX: -9030, originY: 1620, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown04_mainstreet_z+0582.webp', cutHeight: 582, unitsPerPixel: 8.056648, originX: -9030, originY: 1620, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown04_mainstreet_z+1150.webp', cutHeight: 1150, unitsPerPixel: 8.056648, originX: -9030, originY: 1620, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown04_mainstreet_z+1806.webp', cutHeight: 1806, unitsPerPixel: 8.056648, originX: -9030, originY: 1620, width: 2048, height: 1271 },
    ],
  },
  'l4d_vs_smalltown05_houseboat': {
    map: 'l4d_vs_smalltown05_houseboat',
    layers: [
      { image: '/overviews/l4d_vs_smalltown05_houseboat_z+0006.webp', cutHeight: 6, unitsPerPixel: 8.056648, originX: -6530, originY: 4820, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown05_houseboat_z+0262.webp', cutHeight: 262, unitsPerPixel: 8.056648, originX: -6530, originY: 4820, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown05_houseboat_z+0830.webp', cutHeight: 830, unitsPerPixel: 8.056648, originX: -6530, originY: 4820, width: 2048, height: 1271 },
      { image: '/overviews/l4d_vs_smalltown05_houseboat_z+1774.webp', cutHeight: 1774, unitsPerPixel: 8.056648, originX: -6530, originY: 4820, width: 2048, height: 1271 },
    ],
  },
};

/** The overview stack for a map, or null when there is no art for it.
 *
 *  Keys are the names the server reports, including the `vs_` infix for versus
 *  maps and the co-op names for Crash Course, which ships no versus variant. The
 *  second-chance lookup exists because a miss here is silent: the viewer falls
 *  back to auto-fit and simply looks worse, with nothing logged. */
export function overviewFor(map: string): (typeof OVERVIEWS)[string] | null {
  const key = map.toLowerCase();
  if (OVERVIEWS[key]) return OVERVIEWS[key];
  const swapped = key.startsWith('l4d_vs_')
    ? key.replace('l4d_vs_', 'l4d_')
    : key.replace('l4d_', 'l4d_vs_');
  return OVERVIEWS[swapped] ?? null;
}
