/**
 * Map overview layers, generated by tools/gen-overviews.py.
 *
 * Do not edit by hand. Every number here is read back from the engine at
 * capture time, so a typo puts every avatar on that map in the wrong place
 * and nothing reports an error.
 *
 * Each map is a stack of horizontal slices cut at different camera heights,
 * ascending. A layer shows everything below its cut height and nothing above,
 * so the right one to draw is the lowest whose cut is still above the players.
 * All layers of a map share one transform, so switching between them needs no
 * repositioning.
 *
 * This module has no imports, deliberately: it is loaded by the browser as
 * well as the server. See src/mapTransform.ts for the matching named types.
 */

export const OVERVIEWS: Record<string, {
  map: string;
  layers: {
    image: string;
    cutHeight: number;
    unitsPerPixel: number;
    originX: number;
    originY: number;
    width: number;
    height: number;
  }[];
  contentBox: { x0: number; y0: number; x1: number; y1: number };
}> = {
  'l4d_garage01_alleys': {
    map: 'l4d_garage01_alleys',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_garage01_alleys_z-0186.16x.webp', cutHeight: -186, unitsPerPixel: 2.819827, originX: -16747, originY: 1246, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_garage01_alleys_z+0070.16x.webp', cutHeight: 70, unitsPerPixel: 2.819827, originX: -16747, originY: 1246, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_garage01_alleys_z+0326.16x.webp', cutHeight: 326, unitsPerPixel: 2.819827, originX: -16747, originY: 1246, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_garage01_alleys_z+0894.16x.webp', cutHeight: 894, unitsPerPixel: 2.819827, originX: -16747, originY: 1246, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_garage01_alleys_z+0990.16x.webp', cutHeight: 990, unitsPerPixel: 2.819827, originX: -16747, originY: 1246, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 1451, y0: 348, x1: 7302, y1: 4765 },
  },
  'l4d_garage02_lots': {
    map: 'l4d_garage02_lots',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_garage02_lots_z-0154.16x.webp', cutHeight: -154, unitsPerPixel: 2.014162, originX: -4243.01, originY: 8128, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_garage02_lots_z+0134.16x.webp', cutHeight: 134, unitsPerPixel: 2.014162, originX: -4243.01, originY: 8128, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_garage02_lots_z+0518.16x.webp', cutHeight: 518, unitsPerPixel: 2.014162, originX: -4243.01, originY: 8128, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_garage02_lots_z+1086.16x.webp', cutHeight: 1086, unitsPerPixel: 2.014162, originX: -4243.01, originY: 8128, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_garage02_lots_z+1214.16x.webp', cutHeight: 1214, unitsPerPixel: 2.014162, originX: -4243.01, originY: 8128, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 1248, y0: 0, x1: 6969, y1: 5084 },
  },
  'l4d_vs_airport01_greenhouse': {
    map: 'l4d_vs_airport01_greenhouse',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport01_greenhouse_z+0102.16x.webp', cutHeight: 102, unitsPerPixel: 1.611330, originX: -1973.01, originY: 5791, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport01_greenhouse_z+0262.16x.webp', cutHeight: 262, unitsPerPixel: 1.611330, originX: -1973.01, originY: 5791, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport01_greenhouse_z+0518.16x.webp', cutHeight: 518, unitsPerPixel: 1.611330, originX: -1973.01, originY: 5791, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport01_greenhouse_z+0774.16x.webp', cutHeight: 774, unitsPerPixel: 1.611330, originX: -1973.01, originY: 5791, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport01_greenhouse_z+1030.16x.webp', cutHeight: 1030, unitsPerPixel: 1.611330, originX: -1973.01, originY: 5791, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport01_greenhouse_z+1598.16x.webp', cutHeight: 1598, unitsPerPixel: 1.611330, originX: -1973.01, originY: 5791, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport01_greenhouse_z+1806.16x.webp', cutHeight: 1806, unitsPerPixel: 1.611330, originX: -1973.01, originY: 5791, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 1264, y0: 0, x1: 7938, y1: 5084 },
  },
  'l4d_vs_airport02_offices': {
    map: 'l4d_vs_airport02_offices',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport02_offices_z+0070.16x.webp', cutHeight: 70, unitsPerPixel: 1.409913, originX: 1327.99, originY: 7842, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport02_offices_z+0198.16x.webp', cutHeight: 198, unitsPerPixel: 1.409913, originX: 1327.99, originY: 7842, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport02_offices_z+0326.16x.webp', cutHeight: 326, unitsPerPixel: 1.409913, originX: 1327.99, originY: 7842, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport02_offices_z+0454.16x.webp', cutHeight: 454, unitsPerPixel: 1.409913, originX: 1327.99, originY: 7842, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport02_offices_z+0582.16x.webp', cutHeight: 582, unitsPerPixel: 1.409913, originX: 1327.99, originY: 7842, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport02_offices_z+0710.16x.webp', cutHeight: 710, unitsPerPixel: 1.409913, originX: 1327.99, originY: 7842, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport02_offices_z+0838.16x.webp', cutHeight: 838, unitsPerPixel: 1.409913, originX: 1327.99, originY: 7842, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport02_offices_z+0966.16x.webp', cutHeight: 966, unitsPerPixel: 1.409913, originX: 1327.99, originY: 7842, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport02_offices_z+1150.16x.webp', cutHeight: 1150, unitsPerPixel: 1.409913, originX: 1327.99, originY: 7842, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport02_offices_z+1534.16x.webp', cutHeight: 1534, unitsPerPixel: 1.409913, originX: 1327.99, originY: 7842, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport02_offices_z+2030.16x.webp', cutHeight: 2030, unitsPerPixel: 1.409913, originX: 1327.99, originY: 7842, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 873, y0: 0, x1: 7178, y1: 5084 },
  },
  'l4d_vs_airport03_garage': {
    map: 'l4d_vs_airport03_garage',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport03_garage_z+0070.16x.webp', cutHeight: 70, unitsPerPixel: 2.316286, originX: -13116.5, originY: 6425, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport03_garage_z+0326.16x.webp', cutHeight: 326, unitsPerPixel: 2.316286, originX: -13116.5, originY: 6425, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport03_garage_z+0582.16x.webp', cutHeight: 582, unitsPerPixel: 2.316286, originX: -13116.5, originY: 6425, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport03_garage_z+1150.16x.webp', cutHeight: 1150, unitsPerPixel: 2.316286, originX: -13116.5, originY: 6425, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport03_garage_z+1934.16x.webp', cutHeight: 1934, unitsPerPixel: 2.316286, originX: -13116.5, originY: 6425, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 2140, y0: 11, x1: 5885, y1: 5047 },
  },
  'l4d_vs_airport04_terminal': {
    map: 'l4d_vs_airport04_terminal',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport04_terminal_z+0070.16x.webp', cutHeight: 70, unitsPerPixel: 1.309205, originX: -3491.51, originY: 6467, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport04_terminal_z+0198.16x.webp', cutHeight: 198, unitsPerPixel: 1.309205, originX: -3491.51, originY: 6467, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport04_terminal_z+0326.16x.webp', cutHeight: 326, unitsPerPixel: 1.309205, originX: -3491.51, originY: 6467, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport04_terminal_z+0454.16x.webp', cutHeight: 454, unitsPerPixel: 1.309205, originX: -3491.51, originY: 6467, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport04_terminal_z+0582.16x.webp', cutHeight: 582, unitsPerPixel: 1.309205, originX: -3491.51, originY: 6467, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport04_terminal_z+0766.16x.webp', cutHeight: 766, unitsPerPixel: 1.309205, originX: -3491.51, originY: 6467, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport04_terminal_z+1150.16x.webp', cutHeight: 1150, unitsPerPixel: 1.309205, originX: -3491.51, originY: 6467, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport04_terminal_z+4030.16x.webp', cutHeight: 4030, unitsPerPixel: 1.309205, originX: -3491.51, originY: 6467, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 1018, y0: 0, x1: 8192, y1: 5084 },
  },
  'l4d_vs_airport05_runway': {
    map: 'l4d_vs_airport05_runway',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport05_runway_z-0378.16x.webp', cutHeight: -378, unitsPerPixel: 3.121951, originX: -13298.5, originY: 17864, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport05_runway_z-0122.16x.webp', cutHeight: -122, unitsPerPixel: 3.121951, originX: -13298.5, originY: 17864, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport05_runway_z+0134.16x.webp', cutHeight: 134, unitsPerPixel: 3.121951, originX: -13298.5, originY: 17864, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport05_runway_z+0390.16x.webp', cutHeight: 390, unitsPerPixel: 3.121951, originX: -13298.5, originY: 17864, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport05_runway_z+0958.16x.webp', cutHeight: 958, unitsPerPixel: 3.121951, originX: -13298.5, originY: 17864, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_airport05_runway_z+8158.16x.webp', cutHeight: 8158, unitsPerPixel: 3.121951, originX: -13298.5, originY: 17864, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 1018, y0: 0, x1: 8192, y1: 5022 },
  },
  'l4d_vs_farm01_hilltop': {
    map: 'l4d_vs_farm01_hilltop',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm01_hilltop_z+0326.16x.webp', cutHeight: 326, unitsPerPixel: 1.812746, originX: -16547, originY: -6299, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm01_hilltop_z+0582.16x.webp', cutHeight: 582, unitsPerPixel: 1.812746, originX: -16547, originY: -6299, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm01_hilltop_z+0838.16x.webp', cutHeight: 838, unitsPerPixel: 1.812746, originX: -16547, originY: -6299, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm01_hilltop_z+1406.16x.webp', cutHeight: 1406, unitsPerPixel: 1.812746, originX: -16547, originY: -6299, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm01_hilltop_z+2270.16x.webp', cutHeight: 2270, unitsPerPixel: 1.812746, originX: -16547, originY: -6299, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 1559, y0: 0, x1: 7464, y1: 5084 },
  },
  'l4d_vs_farm02_traintunnel': {
    map: 'l4d_vs_farm02_traintunnel',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm02_traintunnel_z+0006.16x.webp', cutHeight: 6, unitsPerPixel: 1.712038, originX: -11939.5, originY: -4779, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm02_traintunnel_z+0134.16x.webp', cutHeight: 134, unitsPerPixel: 1.712038, originX: -11939.5, originY: -4779, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm02_traintunnel_z+0262.16x.webp', cutHeight: 262, unitsPerPixel: 1.712038, originX: -11939.5, originY: -4779, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm02_traintunnel_z+0390.16x.webp', cutHeight: 390, unitsPerPixel: 1.712038, originX: -11939.5, originY: -4779, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm02_traintunnel_z+0518.16x.webp', cutHeight: 518, unitsPerPixel: 1.712038, originX: -11939.5, originY: -4779, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm02_traintunnel_z+0646.16x.webp', cutHeight: 646, unitsPerPixel: 1.712038, originX: -11939.5, originY: -4779, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm02_traintunnel_z+0830.16x.webp', cutHeight: 830, unitsPerPixel: 1.712038, originX: -11939.5, originY: -4779, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm02_traintunnel_z+1214.16x.webp', cutHeight: 1214, unitsPerPixel: 1.712038, originX: -11939.5, originY: -4779, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm02_traintunnel_z+2270.16x.webp', cutHeight: 2270, unitsPerPixel: 1.712038, originX: -11939.5, originY: -4779, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 379, y0: 0, x1: 7431, y1: 5032 },
  },
  'l4d_vs_farm03_bridge': {
    map: 'l4d_vs_farm03_bridge',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm03_bridge_z+0134.16x.webp', cutHeight: 134, unitsPerPixel: 2.014162, originX: -3483.01, originY: -8921, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm03_bridge_z+0390.16x.webp', cutHeight: 390, unitsPerPixel: 2.014162, originX: -3483.01, originY: -8921, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm03_bridge_z+0646.16x.webp', cutHeight: 646, unitsPerPixel: 2.014162, originX: -3483.01, originY: -8921, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm03_bridge_z+1214.16x.webp', cutHeight: 1214, unitsPerPixel: 2.014162, originX: -3483.01, originY: -8921, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm03_bridge_z+1806.16x.webp', cutHeight: 1806, unitsPerPixel: 2.014162, originX: -3483.01, originY: -8921, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 1068, y0: 0, x1: 7211, y1: 3438 },
  },
  'l4d_vs_farm04_barn': {
    map: 'l4d_vs_farm04_barn',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm04_barn_z-0058.16x.webp', cutHeight: -58, unitsPerPixel: 2.215578, originX: 3249.99, originY: -241, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm04_barn_z+0070.16x.webp', cutHeight: 70, unitsPerPixel: 2.215578, originX: 3249.99, originY: -241, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm04_barn_z+0198.16x.webp', cutHeight: 198, unitsPerPixel: 2.215578, originX: 3249.99, originY: -241, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm04_barn_z+0326.16x.webp', cutHeight: 326, unitsPerPixel: 2.215578, originX: 3249.99, originY: -241, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm04_barn_z+0454.16x.webp', cutHeight: 454, unitsPerPixel: 2.215578, originX: 3249.99, originY: -241, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm04_barn_z+0582.16x.webp', cutHeight: 582, unitsPerPixel: 2.215578, originX: 3249.99, originY: -241, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm04_barn_z+0710.16x.webp', cutHeight: 710, unitsPerPixel: 2.215578, originX: 3249.99, originY: -241, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm04_barn_z+0894.16x.webp', cutHeight: 894, unitsPerPixel: 2.215578, originX: 3249.99, originY: -241, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm04_barn_z+1278.16x.webp', cutHeight: 1278, unitsPerPixel: 2.215578, originX: 3249.99, originY: -241, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm04_barn_z+2286.16x.webp', cutHeight: 2286, unitsPerPixel: 2.215578, originX: 3249.99, originY: -241, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 1282, y0: 0, x1: 5059, y1: 5084 },
  },
  'l4d_vs_farm05_cornfield': {
    map: 'l4d_vs_farm05_cornfield',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm05_cornfield_z+0198.16x.webp', cutHeight: 198, unitsPerPixel: 1.208497, originX: 3891, originY: 4893, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm05_cornfield_z+0454.16x.webp', cutHeight: 454, unitsPerPixel: 1.208497, originX: 3891, originY: 4893, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm05_cornfield_z+0710.16x.webp', cutHeight: 710, unitsPerPixel: 1.208497, originX: 3891, originY: 4893, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm05_cornfield_z+1278.16x.webp', cutHeight: 1278, unitsPerPixel: 1.208497, originX: 3891, originY: 4893, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_farm05_cornfield_z+1934.16x.webp', cutHeight: 1934, unitsPerPixel: 1.208497, originX: 3891, originY: 4893, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 169, y0: 0, x1: 8192, y1: 5084 },
  },
  'l4d_vs_hospital01_apartment': {
    map: 'l4d_vs_hospital01_apartment',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital01_apartment_z-0177.16x.webp', cutHeight: -177, unitsPerPixel: 1.409913, originX: -2067.01, originY: 6609, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital01_apartment_z-0114.16x.webp', cutHeight: -114, unitsPerPixel: 1.409913, originX: -2067.01, originY: 6609, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital01_apartment_z+0014.16x.webp', cutHeight: 14, unitsPerPixel: 1.409913, originX: -2067.01, originY: 6609, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital01_apartment_z+0142.16x.webp', cutHeight: 142, unitsPerPixel: 1.409913, originX: -2067.01, originY: 6609, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital01_apartment_z+0270.16x.webp', cutHeight: 270, unitsPerPixel: 1.409913, originX: -2067.01, originY: 6609, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital01_apartment_z+0398.16x.webp', cutHeight: 398, unitsPerPixel: 1.409913, originX: -2067.01, originY: 6609, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital01_apartment_z+0526.16x.webp', cutHeight: 526, unitsPerPixel: 1.409913, originX: -2067.01, originY: 6609, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital01_apartment_z+0654.16x.webp', cutHeight: 654, unitsPerPixel: 1.409913, originX: -2067.01, originY: 6609, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital01_apartment_z+0782.16x.webp', cutHeight: 782, unitsPerPixel: 1.409913, originX: -2067.01, originY: 6609, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital01_apartment_z+0910.16x.webp', cutHeight: 910, unitsPerPixel: 1.409913, originX: -2067.01, originY: 6609, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital01_apartment_z+1038.16x.webp', cutHeight: 1038, unitsPerPixel: 1.409913, originX: -2067.01, originY: 6609, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital01_apartment_z+1166.16x.webp', cutHeight: 1166, unitsPerPixel: 1.409913, originX: -2067.01, originY: 6609, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital01_apartment_z+1294.16x.webp', cutHeight: 1294, unitsPerPixel: 1.409913, originX: -2067.01, originY: 6609, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital01_apartment_z+4558.16x.webp', cutHeight: 4558, unitsPerPixel: 1.409913, originX: -2067.01, originY: 6609, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 1284, y0: 0, x1: 6643, y1: 5084 },
  },
  'l4d_vs_hospital02_subway': {
    map: 'l4d_vs_hospital02_subway',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital02_subway_z-0438.16x.webp', cutHeight: -438, unitsPerPixel: 1.913454, originX: -977.507, originY: 9796, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital02_subway_z-0386.16x.webp', cutHeight: -386, unitsPerPixel: 1.913454, originX: -977.507, originY: 9796, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital02_subway_z-0258.16x.webp', cutHeight: -258, unitsPerPixel: 1.913454, originX: -977.507, originY: 9796, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital02_subway_z-0130.16x.webp', cutHeight: -130, unitsPerPixel: 1.913454, originX: -977.507, originY: 9796, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital02_subway_z-0002.16x.webp', cutHeight: -2, unitsPerPixel: 1.913454, originX: -977.507, originY: 9796, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital02_subway_z+0126.16x.webp', cutHeight: 126, unitsPerPixel: 1.913454, originX: -977.507, originY: 9796, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital02_subway_z+0254.16x.webp', cutHeight: 254, unitsPerPixel: 1.913454, originX: -977.507, originY: 9796, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital02_subway_z+0382.16x.webp', cutHeight: 382, unitsPerPixel: 1.913454, originX: -977.507, originY: 9796, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital02_subway_z+0510.16x.webp', cutHeight: 510, unitsPerPixel: 1.913454, originX: -977.507, originY: 9796, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital02_subway_z+0638.16x.webp', cutHeight: 638, unitsPerPixel: 1.913454, originX: -977.507, originY: 9796, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital02_subway_z+0766.16x.webp', cutHeight: 766, unitsPerPixel: 1.913454, originX: -977.507, originY: 9796, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital02_subway_z+0894.16x.webp', cutHeight: 894, unitsPerPixel: 1.913454, originX: -977.507, originY: 9796, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital02_subway_z+1886.16x.webp', cutHeight: 1886, unitsPerPixel: 1.913454, originX: -977.507, originY: 9796, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 1293, y0: 36, x1: 7151, y1: 3908 },
  },
  'l4d_vs_hospital03_sewers': {
    map: 'l4d_vs_hospital03_sewers',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z-0412.16x.webp', cutHeight: -412, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z-0364.16x.webp', cutHeight: -364, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z-0236.16x.webp', cutHeight: -236, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z-0108.16x.webp', cutHeight: -108, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z+0020.16x.webp', cutHeight: 20, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z+0148.16x.webp', cutHeight: 148, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z+0276.16x.webp', cutHeight: 276, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z+0404.16x.webp', cutHeight: 404, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z+0532.16x.webp', cutHeight: 532, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z+0660.16x.webp', cutHeight: 660, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z+0788.16x.webp', cutHeight: 788, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z+0916.16x.webp', cutHeight: 916, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z+1044.16x.webp', cutHeight: 1044, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z+1172.16x.webp', cutHeight: 1172, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital03_sewers_z+6062.16x.webp', cutHeight: 6062, unitsPerPixel: 2.014162, originX: 3923.99, originY: 14137, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 993, y0: 0, x1: 5678, y1: 5084 },
  },
  'l4d_vs_hospital04_interior': {
    map: 'l4d_vs_hospital04_interior',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital04_interior_z+0070.16x.webp', cutHeight: 70, unitsPerPixel: 0.805665, originX: 9285, originY: 15693, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital04_interior_z+0198.16x.webp', cutHeight: 198, unitsPerPixel: 0.805665, originX: 9285, originY: 15693, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital04_interior_z+0326.16x.webp', cutHeight: 326, unitsPerPixel: 0.805665, originX: 9285, originY: 15693, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital04_interior_z+0454.16x.webp', cutHeight: 454, unitsPerPixel: 0.805665, originX: 9285, originY: 15693, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital04_interior_z+0582.16x.webp', cutHeight: 582, unitsPerPixel: 0.805665, originX: 9285, originY: 15693, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital04_interior_z+0710.16x.webp', cutHeight: 710, unitsPerPixel: 0.805665, originX: 9285, originY: 15693, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital04_interior_z+0894.16x.webp', cutHeight: 894, unitsPerPixel: 0.805665, originX: 9285, originY: 15693, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital04_interior_z+1278.16x.webp', cutHeight: 1278, unitsPerPixel: 0.805665, originX: 9285, originY: 15693, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital04_interior_z+5574.16x.webp', cutHeight: 5574, unitsPerPixel: 0.805665, originX: 9285, originY: 15693, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital04_interior_z+5702.16x.webp', cutHeight: 5702, unitsPerPixel: 0.805665, originX: 9285, originY: 15693, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital04_interior_z+5830.16x.webp', cutHeight: 5830, unitsPerPixel: 0.805665, originX: 9285, originY: 15693, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital04_interior_z+6014.16x.webp', cutHeight: 6014, unitsPerPixel: 0.805665, originX: 9285, originY: 15693, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital04_interior_z+6398.16x.webp', cutHeight: 6398, unitsPerPixel: 0.805665, originX: 9285, originY: 15693, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital04_interior_z+7646.16x.webp', cutHeight: 7646, unitsPerPixel: 0.805665, originX: 9285, originY: 15693, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 0, y0: 0, x1: 8192, y1: 5084 },
  },
  'l4d_vs_hospital05_rooftop': {
    map: 'l4d_vs_hospital05_rooftop',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital05_rooftop_z+0262.16x.webp', cutHeight: 262, unitsPerPixel: 0.704957, originX: 3647.5, originY: 9768, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital05_rooftop_z+0446.16x.webp', cutHeight: 446, unitsPerPixel: 0.704957, originX: 3647.5, originY: 9768, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital05_rooftop_z+0830.16x.webp', cutHeight: 830, unitsPerPixel: 0.704957, originX: 3647.5, originY: 9768, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital05_rooftop_z+5574.16x.webp', cutHeight: 5574, unitsPerPixel: 0.704957, originX: 3647.5, originY: 9768, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital05_rooftop_z+5702.16x.webp', cutHeight: 5702, unitsPerPixel: 0.704957, originX: 3647.5, originY: 9768, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital05_rooftop_z+5830.16x.webp', cutHeight: 5830, unitsPerPixel: 0.704957, originX: 3647.5, originY: 9768, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital05_rooftop_z+5958.16x.webp', cutHeight: 5958, unitsPerPixel: 0.704957, originX: 3647.5, originY: 9768, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital05_rooftop_z+6086.16x.webp', cutHeight: 6086, unitsPerPixel: 0.704957, originX: 3647.5, originY: 9768, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital05_rooftop_z+6214.16x.webp', cutHeight: 6214, unitsPerPixel: 0.704957, originX: 3647.5, originY: 9768, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital05_rooftop_z+6342.16x.webp', cutHeight: 6342, unitsPerPixel: 0.704957, originX: 3647.5, originY: 9768, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital05_rooftop_z+6526.16x.webp', cutHeight: 6526, unitsPerPixel: 0.704957, originX: 3647.5, originY: 9768, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital05_rooftop_z+6910.16x.webp', cutHeight: 6910, unitsPerPixel: 0.704957, originX: 3647.5, originY: 9768, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_hospital05_rooftop_z+8158.16x.webp', cutHeight: 8158, unitsPerPixel: 0.704957, originX: 3647.5, originY: 9768, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 35, y0: 0, x1: 8179, y1: 5084 },
  },
  'l4d_vs_smalltown01_caves': {
    map: 'l4d_vs_smalltown01_caves',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown01_caves_z-0314.16x.webp', cutHeight: -314, unitsPerPixel: 2.416994, originX: -21215, originY: -3809, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown01_caves_z-0058.16x.webp', cutHeight: -58, unitsPerPixel: 2.416994, originX: -21215, originY: -3809, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown01_caves_z+0198.16x.webp', cutHeight: 198, unitsPerPixel: 2.416994, originX: -21215, originY: -3809, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown01_caves_z+0454.16x.webp', cutHeight: 454, unitsPerPixel: 2.416994, originX: -21215, originY: -3809, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown01_caves_z+0710.16x.webp', cutHeight: 710, unitsPerPixel: 2.416994, originX: -21215, originY: -3809, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown01_caves_z+1278.16x.webp', cutHeight: 1278, unitsPerPixel: 2.416994, originX: -21215, originY: -3809, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown01_caves_z+1566.16x.webp', cutHeight: 1566, unitsPerPixel: 2.416994, originX: -21215, originY: -3809, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 2181, y0: 13, x1: 5177, y1: 5084 },
  },
  'l4d_vs_smalltown02_drainage': {
    map: 'l4d_vs_smalltown02_drainage',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown02_drainage_z-0634.16x.webp', cutHeight: -634, unitsPerPixel: 1.208497, originX: -13662, originY: -3090, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown02_drainage_z-0506.16x.webp', cutHeight: -506, unitsPerPixel: 1.208497, originX: -13662, originY: -3090, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown02_drainage_z-0378.16x.webp', cutHeight: -378, unitsPerPixel: 1.208497, originX: -13662, originY: -3090, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown02_drainage_z-0250.16x.webp', cutHeight: -250, unitsPerPixel: 1.208497, originX: -13662, originY: -3090, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown02_drainage_z-0122.16x.webp', cutHeight: -122, unitsPerPixel: 1.208497, originX: -13662, originY: -3090, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown02_drainage_z+0006.16x.webp', cutHeight: 6, unitsPerPixel: 1.208497, originX: -13662, originY: -3090, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown02_drainage_z+0134.16x.webp', cutHeight: 134, unitsPerPixel: 1.208497, originX: -13662, originY: -3090, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown02_drainage_z+0262.16x.webp', cutHeight: 262, unitsPerPixel: 1.208497, originX: -13662, originY: -3090, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown02_drainage_z+0446.16x.webp', cutHeight: 446, unitsPerPixel: 1.208497, originX: -13662, originY: -3090, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown02_drainage_z+0830.16x.webp', cutHeight: 830, unitsPerPixel: 1.208497, originX: -13662, originY: -3090, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown02_drainage_z+1380.16x.webp', cutHeight: 1380, unitsPerPixel: 1.208497, originX: -13662, originY: -3090, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 1428, y0: 0, x1: 8192, y1: 5030 },
  },
  'l4d_vs_smalltown03_ranchhouse': {
    map: 'l4d_vs_smalltown03_ranchhouse',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown03_ranchhouse_z+0038.16x.webp', cutHeight: 38, unitsPerPixel: 2.114870, originX: -16206.5, originY: 2506, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown03_ranchhouse_z+0262.16x.webp', cutHeight: 262, unitsPerPixel: 2.114870, originX: -16206.5, originY: 2506, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown03_ranchhouse_z+0646.16x.webp', cutHeight: 646, unitsPerPixel: 2.114870, originX: -16206.5, originY: 2506, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown03_ranchhouse_z+1214.16x.webp', cutHeight: 1214, unitsPerPixel: 2.114870, originX: -16206.5, originY: 2506, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown03_ranchhouse_z+1902.16x.webp', cutHeight: 1902, unitsPerPixel: 2.114870, originX: -16206.5, originY: 2506, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 751, y0: 126, x1: 7248, y1: 5084 },
  },
  'l4d_vs_smalltown04_mainstreet': {
    map: 'l4d_vs_smalltown04_mainstreet',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown04_mainstreet_z-0026.16x.webp', cutHeight: -26, unitsPerPixel: 2.014162, originX: -9030.01, originY: 1620, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown04_mainstreet_z+0198.16x.webp', cutHeight: 198, unitsPerPixel: 2.014162, originX: -9030.01, originY: 1620, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown04_mainstreet_z+0582.16x.webp', cutHeight: 582, unitsPerPixel: 2.014162, originX: -9030.01, originY: 1620, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown04_mainstreet_z+1150.16x.webp', cutHeight: 1150, unitsPerPixel: 2.014162, originX: -9030.01, originY: 1620, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown04_mainstreet_z+1806.16x.webp', cutHeight: 1806, unitsPerPixel: 2.014162, originX: -9030.01, originY: 1620, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 0, y0: 0, x1: 7709, y1: 4181 },
  },
  'l4d_vs_smalltown05_houseboat': {
    map: 'l4d_vs_smalltown05_houseboat',
    layers: [
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown05_houseboat_z+0006.16x.webp', cutHeight: 6, unitsPerPixel: 2.014162, originX: -6530.01, originY: 4820, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown05_houseboat_z+0262.16x.webp', cutHeight: 262, unitsPerPixel: 2.014162, originX: -6530.01, originY: 4820, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown05_houseboat_z+0830.16x.webp', cutHeight: 830, unitsPerPixel: 2.014162, originX: -6530.01, originY: 4820, width: 8192, height: 5084 },
      { image: 'https://pub-ff0d7050ac0246ccb3ca65b0e6297940.r2.dev/overviews/l4d_vs_smalltown05_houseboat_z+1774.16x.webp', cutHeight: 1774, unitsPerPixel: 2.014162, originX: -6530.01, originY: 4820, width: 8192, height: 5084 },
    ],
    contentBox: { x0: 1478, y0: 0, x1: 7437, y1: 5084 },
  },
};

/** The overview stack for a map, or null when there is no art for it.
 *
 *  Keys are the names the server reports, including the `vs_` infix for versus
 *  maps and the co-op names for Crash Course, which ships no versus variant. The
 *  second-chance lookup exists because a miss here is silent: the viewer falls
 *  back to auto-fit and simply looks worse, with nothing logged. */
export function overviewFor(map: string): (typeof OVERVIEWS)[string] | null {
  const key = map.toLowerCase();
  if (OVERVIEWS[key]) return OVERVIEWS[key];
  const swapped = key.startsWith('l4d_vs_')
    ? key.replace('l4d_vs_', 'l4d_')
    : key.replace('l4d_', 'l4d_vs_');
  return OVERVIEWS[swapped] ?? null;
}
